"use strict";
/**
 * (C) Copyright IBM Corp. 2025.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
/**
 * IBM OpenAPI SDK Code Generator Version: 3.108.0-56772134-20251111-102802
 */
var extend = require("extend");
var ibm_cloud_sdk_core_1 = require("ibm-cloud-sdk-core");
var common_1 = require("../lib/common");
/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 1.0.0
 */
var DrAutomationServiceV1 = /** @class */ (function (_super) {
    __extends(DrAutomationServiceV1, _super);
    /**
     * Construct a DrAutomationServiceV1 object.
     *
     * @param {Object} options - Options for the service.
     * @param {string} [options.serviceUrl] - The base URL for the service
     * @param {OutgoingHttpHeaders} [options.headers] - Default headers that shall be included with every request to the service.
     * @param {Authenticator} options.authenticator - The Authenticator object used to authenticate requests to the service
     * @constructor
     * @returns {DrAutomationServiceV1}
     */
    function DrAutomationServiceV1(options) {
        var _this = this;
        options = options || {};
        _this = _super.call(this, options) || this;
        if (options.serviceUrl) {
            _this.setServiceUrl(options.serviceUrl);
        }
        else {
            _this.setServiceUrl(DrAutomationServiceV1.DEFAULT_SERVICE_URL);
        }
        return _this;
    }
    /*************************
     * Factory method
     ************************/
    /**
     * Constructs an instance of DrAutomationServiceV1 with passed in options and external configuration.
     *
     * @param {UserOptions} [options] - The parameters to send to the service.
     * @param {string} [options.serviceName] - The name of the service to configure
     * @param {Authenticator} [options.authenticator] - The Authenticator object used to authenticate requests to the service
     * @param {string} [options.serviceUrl] - The base URL for the service
     * @returns {DrAutomationServiceV1}
     */
    DrAutomationServiceV1.newInstance = function (options) {
        options = options || {};
        if (!options.serviceName) {
            options.serviceName = this.DEFAULT_SERVICE_NAME;
        }
        if (!options.authenticator) {
            options.authenticator = (0, ibm_cloud_sdk_core_1.getAuthenticatorFromEnvironment)(options.serviceName);
        }
        var service = new DrAutomationServiceV1(options);
        service.configureService(options.serviceName);
        if (options.serviceUrl) {
            service.setServiceUrl(options.serviceUrl);
        }
        return service;
    };
    /*************************
     * drAutomationConfig
     ************************/
    /**
     * Updates the API key for the specified service instance.
     *
     * Updating the current API key details for the specified service instance.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} params.apiKey - The new API key value that will replace the existing one.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>>}
     */
    DrAutomationServiceV1.prototype.updateApikey = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId', 'apiKey'];
        var _validParams = ['instanceId', 'apiKey', 'acceptLanguage', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var body = {
            'api_key': _params.apiKey,
        };
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'updateApikey');
        var parameters = {
            options: {
                url: '/drautomation/v1/apikey/{instance_id}',
                method: 'PUT',
                body: body,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Get GRS location pairs based on managed vms.
     *
     * Retrieves the (GRS) location pairs associated with the specified service instance based on managed VMs.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetGRSLocationPairResponse>>}
     */
    DrAutomationServiceV1.prototype.getDrGrsLocationPair = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId'];
        var _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getDrGrsLocationPair');
        var parameters = {
            options: {
                url: '/drautomation/v1/dr_grs_location_pairs/{instance_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Get Disaster recovery locations.
     *
     * Retrieves the list of disaster recovery (DR) locations available for the specified service instance.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetDrLocationsResponse>>}
     */
    DrAutomationServiceV1.prototype.getDrLocations = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId'];
        var _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getDrLocations');
        var parameters = {
            options: {
                url: '/drautomation/v1/dr_locations/{instance_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Get managed vms for the instance.
     *
     * Retrieves the list of disaster recovery (DR) managed virtual machines for the specified service instance.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ManagedVmMapResponse>>}
     */
    DrAutomationServiceV1.prototype.getDrManagedVm = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId'];
        var _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getDrManagedVm');
        var parameters = {
            options: {
                url: '/drautomation/v1/dr_managed_vms/{instance_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Disaster recovery deployment details.
     *
     * Retrieves the disaster recovery (DR) summary details for the specified service instance, including key
     * configuration, status information and managed vm details.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrAutomationGetSummaryResponse>>}
     */
    DrAutomationServiceV1.prototype.getDrSummary = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId'];
        var _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getDrSummary');
        var parameters = {
            options: {
                url: '/drautomation/v1/dr_summary/{instance_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /*************************
     * drAutomationIbmCloud
     ************************/
    /**
     * Get MachineTypes based on selected workspaces.
     *
     * Retrieves the list of supported machine types for the given workspace. This endpoint is used to identify machine
     * types available for disaster recovery automation.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} params.primaryWorkspaceName - The primary Power virtual server workspace name.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {string} [params.standbyWorkspaceName] - The standby Power virtual server workspace name.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.MachineTypesByWorkspace>>}
     */
    DrAutomationServiceV1.prototype.getMachineType = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId', 'primaryWorkspaceName'];
        var _validParams = [
            'instanceId',
            'primaryWorkspaceName',
            'acceptLanguage',
            'standbyWorkspaceName',
            'signal',
            'headers',
        ];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var query = {
            'primary_workspace_name': _params.primaryWorkspaceName,
            'standby_workspace_name': _params.standbyWorkspaceName,
        };
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getMachineType');
        var parameters = {
            options: {
                url: '/drautomation/v1/machinetypes/{instance_id}',
                method: 'GET',
                qs: query,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * List of primary and standby powervs workspaces.
     *
     * Retrieves the power virtual server workspaces for primary and standby orchestrator based on location id.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} params.locationId - Location ID value.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrData>>}
     */
    DrAutomationServiceV1.prototype.getPowervsWorkspaces = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId', 'locationId'];
        var _validParams = ['instanceId', 'locationId', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var query = {
            'location_id': _params.locationId,
        };
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getPowervsWorkspaces');
        var parameters = {
            options: {
                url: '/drautomation/v1/powervs_workspaces/{instance_id}',
                method: 'GET',
                qs: query,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /*************************
     * drAutomationManageDr
     ************************/
    /**
     * Create DR Deployment.
     *
     * Creates DR Deployment by creating Orchestrator instance in the given PowerVS workspace and configuration.
     * Orchestrator instance can be used to manage multiple virtual servers and ensure continuous availability. For more
     * details, refer Deploying the Orchestrator -
     * https://cloud.ibm.com/docs/dr-automation-powervs?topic=dr-automation-powervs-idep-the-orch.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} params.locationId - The location or data center identifier where the service instance is deployed.
     * @param {string} params.machineType - The machine type used for deploying orchestrator.
     * @param {string} params.orchestratorLocationType - The cloud location where your orchestator need to be created.
     * @param {string} params.orchestratorName - The username used for the orchestrator.
     * @param {string} params.orchestratorPassword - The password that you can use to access your orchestrator.
     * @param {string} params.orchestratorWorkspaceId - The unique identifier orchestrator workspace.
     * @param {string} [params.apiKey] - The api Key of the service instance for deploying the disaster recovery service.
     * @param {string} [params.clientId] - The Client Id created for MFA authentication API.
     * @param {string} [params.clientSecret] - The client secret created for MFA authentication API.
     * @param {string} [params.guid] - The global unique identifier of the service instance.
     * @param {boolean} [params.orchestratorHa] - Indicates whether the orchestrator High Availability (HA) is enabled for
     * the service instance.
     * @param {string} [params.proxyIp] - Proxy IP for the Communication between Orchestrator and Service broker.
     * @param {string} [params.regionId] - The power virtual server region where the service instance is deployed.
     * @param {string} [params.resourceInstance] - The uniquie identifier of the associated IBM Cloud resource instance.
     * @param {string} [params.secret] - The secret name or identifier used for retrieving credentials from secrets
     * manager.
     * @param {string} [params.secretGroup] - The secret group name in IBM Cloud Secrets Manager containing sensitive data
     * for the service instance.
     * @param {string} [params.sshKeyName] - The name of the SSH key used for deploying the orchestator.
     * @param {string} [params.standbyMachineType] - The machine type used for deploying standby virtual machines.
     * @param {string} [params.standbyOrchestratorName] - The username for the standby orchestrator management interface.
     * @param {string} [params.standbyOrchestratorWorkspaceId] - The unique identifier of the standby orchestrator
     * workspace.
     * @param {string} [params.standbyTier] - The storage tier used for deploying standby orchestrator.
     * @param {string} [params.tenantName] - The tenant name for MFA authentication API.
     * @param {string} [params.tier] - The storage tier used for deploying primary orchestrator.
     * @param {string} [params.standByRedeploy] - Flag to indicate if standby should be redeployed (must be "true" or
     * "false").
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {boolean} [params.acceptsIncomplete] - A value of true indicates that both the IBM Cloud platform and the
     * requesting client support asynchronous deprovisioning.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>>}
     */
    DrAutomationServiceV1.prototype.createManageDr = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = [
            'instanceId',
            'locationId',
            'machineType',
            'orchestratorLocationType',
            'orchestratorName',
            'orchestratorPassword',
            'orchestratorWorkspaceId',
        ];
        var _validParams = [
            'instanceId',
            'locationId',
            'machineType',
            'orchestratorLocationType',
            'orchestratorName',
            'orchestratorPassword',
            'orchestratorWorkspaceId',
            'apiKey',
            'clientId',
            'clientSecret',
            'guid',
            'orchestratorHa',
            'proxyIp',
            'regionId',
            'resourceInstance',
            'secret',
            'secretGroup',
            'sshKeyName',
            'standbyMachineType',
            'standbyOrchestratorName',
            'standbyOrchestratorWorkspaceId',
            'standbyTier',
            'tenantName',
            'tier',
            'standByRedeploy',
            'acceptLanguage',
            'acceptsIncomplete',
            'signal',
            'headers',
        ];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var body = {
            'location_id': _params.locationId,
            'machine_type': _params.machineType,
            'orchestrator_location_type': _params.orchestratorLocationType,
            'orchestrator_name': _params.orchestratorName,
            'orchestrator_password': _params.orchestratorPassword,
            'orchestrator_workspace_id': _params.orchestratorWorkspaceId,
            'api_key': _params.apiKey,
            'client_id': _params.clientId,
            'client_secret': _params.clientSecret,
            'guid': _params.guid,
            'orchestrator_ha': _params.orchestratorHa,
            'proxy_ip': _params.proxyIp,
            'region_id': _params.regionId,
            'resource_instance': _params.resourceInstance,
            'secret': _params.secret,
            'secret_group': _params.secretGroup,
            'ssh_key_name': _params.sshKeyName,
            'standby_machine_type': _params.standbyMachineType,
            'standby_orchestrator_name': _params.standbyOrchestratorName,
            'standby_orchestrator_workspace_id': _params.standbyOrchestratorWorkspaceId,
            'standby_tier': _params.standbyTier,
            'tenant_name': _params.tenantName,
            'tier': _params.tier,
        };
        var query = {
            'stand_by_redeploy': _params.standByRedeploy,
            'accepts_incomplete': _params.acceptsIncomplete,
        };
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'createManageDr');
        var parameters = {
            options: {
                url: '/drautomation/v1/manage_dr/{instance_id}',
                method: 'POST',
                body: body,
                qs: query,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /*************************
     * drAutomationServiceInstance
     ************************/
    /**
     * View details of Last operation performed on the instance.
     *
     * Retrieves the status of the last operation performed on the specified service instance, such as provisioning,
     * updating, or deprovisioning.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceStatus>>}
     */
    DrAutomationServiceV1.prototype.getLastOperation = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId'];
        var _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getLastOperation');
        var parameters = {
            options: {
                url: '/drautomation/v1/last_operation/{instance_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /*************************
     * drEvents
     ************************/
    /**
     * Get events from the cloud instance since a specific timestamp.
     *
     * Retrieves the list of events from the specified service instance ID.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} [params.time] - (deprecated - use from_time) A time in either ISO 8601 or unix epoch format.
     * @param {string} [params.fromTime] - A from query time in either ISO 8601 or unix epoch format.
     * @param {string} [params.toTime] - A to query time in either ISO 8601 or unix epoch format.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.EventCollection>>}
     */
    DrAutomationServiceV1.prototype.listEvents = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId'];
        var _validParams = [
            'instanceId',
            'time',
            'fromTime',
            'toTime',
            'acceptLanguage',
            'signal',
            'headers',
        ];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var query = {
            'time': _params.time,
            'from_time': _params.fromTime,
            'to_time': _params.toTime,
        };
        var path = {
            'instance_id': _params.instanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'listEvents');
        var parameters = {
            options: {
                url: '/drautomation/v1/service_instances/{instance_id}/events',
                method: 'GET',
                qs: query,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Get a single event.
     *
     * Retrieves the details of a specific event for the given service instance provision ID.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.instanceId - instance id of instance to provision.
     * @param {string} params.eventId - Event ID.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.Event>>}
     */
    DrAutomationServiceV1.prototype.getEvent = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['instanceId', 'eventId'];
        var _validParams = ['instanceId', 'eventId', 'acceptLanguage', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'instance_id': _params.instanceId,
            'event_id': _params.eventId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getEvent');
        var parameters = {
            options: {
                url: '/drautomation/v1/service_instances/{instance_id}/events/{event_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    DrAutomationServiceV1.DEFAULT_SERVICE_URL = 'https://power-dra.cloud.ibm.com';
    DrAutomationServiceV1.DEFAULT_SERVICE_NAME = 'dr_automation_service';
    return DrAutomationServiceV1;
}(ibm_cloud_sdk_core_1.BaseService));
/*************************
 * interfaces
 ************************/
(function (DrAutomationServiceV1) {
    var Event;
    (function (Event) {
        var Constants;
        (function (Constants) {
            /** Level of the event (notice, info, warning, error). */
            var Level;
            (function (Level) {
                Level["NOTICE"] = "notice";
                Level["INFO"] = "info";
                Level["WARNING"] = "warning";
                Level["ERROR"] = "error";
            })(Level = Constants.Level || (Constants.Level = {}));
        })(Constants = Event.Constants || (Event.Constants = {}));
    })(Event = DrAutomationServiceV1.Event || (DrAutomationServiceV1.Event = {}));
})(DrAutomationServiceV1 || (DrAutomationServiceV1 = {}));
module.exports = DrAutomationServiceV1;
//# sourceMappingURL=v1.js.map