/**
 * (C) Copyright IBM Corp. 2025.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * IBM OpenAPI SDK Code Generator Version: 3.108.0-56772134-20251111-102802
 */

import * as extend from 'extend';
import { IncomingHttpHeaders, OutgoingHttpHeaders } from 'http';
import {
  AbortSignal,
  Authenticator,
  BaseService,
  UserOptions,
  getAuthenticatorFromEnvironment,
  validateParams,
} from 'ibm-cloud-sdk-core';
import { getSdkHeaders } from '../lib/common';

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 1.0.0
 */

class DrAutomationServiceV1 extends BaseService {
  static DEFAULT_SERVICE_URL: string = 'https://power-dra.test.cloud.ibm.com';

  static DEFAULT_SERVICE_NAME: string = 'dr_automation_service';

  /*************************
   * Factory method
   ************************/

  /**
   * Constructs an instance of DrAutomationServiceV1 with passed in options and external configuration.
   *
   * @param {UserOptions} [options] - The parameters to send to the service.
   * @param {string} [options.serviceName] - The name of the service to configure
   * @param {Authenticator} [options.authenticator] - The Authenticator object used to authenticate requests to the service
   * @param {string} [options.serviceUrl] - The base URL for the service
   * @returns {DrAutomationServiceV1}
   */

  public static newInstance(options: UserOptions): DrAutomationServiceV1 {
    options = options || {};

    if (!options.serviceName) {
      options.serviceName = this.DEFAULT_SERVICE_NAME;
    }
    if (!options.authenticator) {
      options.authenticator = getAuthenticatorFromEnvironment(options.serviceName);
    }
    const service = new DrAutomationServiceV1(options);
    service.configureService(options.serviceName);
    if (options.serviceUrl) {
      service.setServiceUrl(options.serviceUrl);
    }
    return service;
  }

  /**
   * Construct a DrAutomationServiceV1 object.
   *
   * @param {Object} options - Options for the service.
   * @param {string} [options.serviceUrl] - The base URL for the service
   * @param {OutgoingHttpHeaders} [options.headers] - Default headers that shall be included with every request to the service.
   * @param {Authenticator} options.authenticator - The Authenticator object used to authenticate requests to the service
   * @constructor
   * @returns {DrAutomationServiceV1}
   */
  constructor(options: UserOptions) {
    options = options || {};

    super(options);
    if (options.serviceUrl) {
      this.setServiceUrl(options.serviceUrl);
    } else {
      this.setServiceUrl(DrAutomationServiceV1.DEFAULT_SERVICE_URL);
    }
  }

  /*************************
   * drAutomationConfig
   ************************/

  /**
   * Updates the API key for the specified service instance.
   *
   * Updating the current API key details for the specified service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.apiKey - The new API key value that will replace the existing one.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>>}
   */
  public updateApikey(
    params: DrAutomationServiceV1.UpdateApikeyParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'apiKey'];
    const _validParams = ['instanceId', 'apiKey', 'acceptLanguage', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'api_key': _params.apiKey,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'updateApikey'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/apikey/{instance_id}',
        method: 'PUT',
        body,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get GRS location pairs based on managed vms.
   *
   * Retrieves the (GRS) location pairs associated with the specified service instance based on managed VMs.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetGRSLocationPairResponse>>}
   */
  public getDrGrsLocationPair(
    params: DrAutomationServiceV1.GetDrGrsLocationPairParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetGRSLocationPairResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getDrGrsLocationPair'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_grs_location_pairs/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get Disaster recovery locations.
   *
   * Retrieves the list of disaster recovery (DR) locations available for the specified service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetDrLocationsResponse>>}
   */
  public getDrLocations(
    params: DrAutomationServiceV1.GetDrLocationsParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetDrLocationsResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getDrLocations'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_locations/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get managed vms for the instance.
   *
   * Retrieves the list of disaster recovery (DR) managed virtual machines for the specified service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ManagedVmMapResponse>>}
   */
  public getDrManagedVm(
    params: DrAutomationServiceV1.GetDrManagedVmParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ManagedVmMapResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getDrManagedVm'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_managed_vms/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Disaster recovery deployment details.
   *
   * Retrieves the disaster recovery (DR) summary details for the specified service instance, including key
   * configuration, status information and managed vm details.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrAutomationGetSummaryResponse>>}
   */
  public getDrSummary(
    params: DrAutomationServiceV1.GetDrSummaryParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrAutomationGetSummaryResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getDrSummary'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_summary/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drAutomationIbmCloud
   ************************/

  /**
   * Get MachineTypes based on selected workspaces.
   *
   * Retrieves the list of supported machine types for the given workspace. This endpoint is used to identify machine
   * types available for disaster recovery automation.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.primaryWorkspaceName - The primary Power virtual server workspace name.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.standbyWorkspaceName] - The standby Power virtual server workspace name.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.MachineTypesByWorkspace>>}
   */
  public getMachineType(
    params: DrAutomationServiceV1.GetMachineTypeParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.MachineTypesByWorkspace>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'primaryWorkspaceName'];
    const _validParams = [
      'instanceId',
      'primaryWorkspaceName',
      'acceptLanguage',
      'standbyWorkspaceName',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'primary_workspace_name': _params.primaryWorkspaceName,
      'standby_workspace_name': _params.standbyWorkspaceName,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getMachineType'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/machinetypes/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * List of primary and standby powervs workspaces.
   *
   * Retrieves the power virtual server workspaces for primary and standby orchestrator based on location id.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.locationId - Location ID value.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrData>>}
   */
  public getPowervsWorkspaces(
    params: DrAutomationServiceV1.GetPowervsWorkspacesParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrData>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'locationId'];
    const _validParams = ['instanceId', 'locationId', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'location_id': _params.locationId,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getPowervsWorkspaces'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/powervs_workspaces/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drAutomationManageDr
   ************************/

  /**
   * Create DR Deployment.
   *
   * Creates DR Deployment by creating Orchestrator instance in the given PowerVS workspace and configuration.
   * Orchestrator instance can be used to manage multiple virtual servers and ensure continuous availability. For more
   * details, refer Deploying the Orchestrator -
   * https://cloud.ibm.com/docs/dr-automation-powervs?topic=dr-automation-powervs-idep-the-orch.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.locationId - The location or data center identifier where the service instance is deployed.
   * @param {string} params.machineType - The machine type used for deploying orchestrator.
   * @param {string} params.orchestratorLocationType - The cloud location where your orchestator need to be created.
   * @param {string} params.orchestratorName - The username used for the orchestrator.
   * @param {string} params.orchestratorPassword - The password that you can use to access your orchestrator.
   * @param {string} params.orchestratorWorkspaceId - The unique identifier orchestrator workspace.
   * @param {string} [params.apiKey] - The api Key of the service instance for deploying the disaster recovery service.
   * @param {string} [params.clientId] - The Client Id created for MFA authentication API.
   * @param {string} [params.clientSecret] - The client secret created for MFA authentication API.
   * @param {string} [params.guid] - The global unique identifier of the service instance.
   * @param {boolean} [params.orchestratorHa] - Indicates whether the orchestrator High Availability (HA) is enabled for
   * the service instance.
   * @param {string} [params.proxyIp] - Proxy IP for the Communication between Orchestrator and Service broker.
   * @param {string} [params.regionId] - The power virtual server region where the service instance is deployed.
   * @param {string} [params.resourceInstance] - The uniquie identifier of the associated IBM Cloud resource instance.
   * @param {string} [params.secret] - The secret name or identifier used for retrieving credentials from secrets
   * manager.
   * @param {string} [params.secretGroup] - The secret group name in IBM Cloud Secrets Manager containing sensitive data
   * for the service instance.
   * @param {string} [params.sshKeyName] - The name of the SSH key used for deploying the orchestator.
   * @param {string} [params.standbyMachineType] - The machine type used for deploying standby virtual machines.
   * @param {string} [params.standbyOrchestratorName] - The username for the standby orchestrator management interface.
   * @param {string} [params.standbyOrchestratorWorkspaceId] - The unique identifier of the standby orchestrator
   * workspace.
   * @param {string} [params.standbyTier] - The storage tier used for deploying standby orchestrator.
   * @param {string} [params.tenantName] - The tenant name for MFA authentication API.
   * @param {string} [params.tier] - The storage tier used for deploying primary orchestrator.
   * @param {string} [params.standByRedeploy] - Flag to indicate if standby should be redeployed (must be "true" or
   * "false").
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {boolean} [params.acceptsIncomplete] - A value of true indicates that both the IBM Cloud platform and the
   * requesting client support asynchronous deprovisioning.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>>}
   */
  public createManageDr(
    params: DrAutomationServiceV1.CreateManageDrParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>> {
    const _params = { ...params };
    const _requiredParams = [
      'instanceId',
      'locationId',
      'machineType',
      'orchestratorLocationType',
      'orchestratorName',
      'orchestratorPassword',
      'orchestratorWorkspaceId',
    ];
    const _validParams = [
      'instanceId',
      'locationId',
      'machineType',
      'orchestratorLocationType',
      'orchestratorName',
      'orchestratorPassword',
      'orchestratorWorkspaceId',
      'apiKey',
      'clientId',
      'clientSecret',
      'guid',
      'orchestratorHa',
      'proxyIp',
      'regionId',
      'resourceInstance',
      'secret',
      'secretGroup',
      'sshKeyName',
      'standbyMachineType',
      'standbyOrchestratorName',
      'standbyOrchestratorWorkspaceId',
      'standbyTier',
      'tenantName',
      'tier',
      'standByRedeploy',
      'acceptLanguage',
      'acceptsIncomplete',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'location_id': _params.locationId,
      'machine_type': _params.machineType,
      'orchestrator_location_type': _params.orchestratorLocationType,
      'orchestrator_name': _params.orchestratorName,
      'orchestrator_password': _params.orchestratorPassword,
      'orchestrator_workspace_id': _params.orchestratorWorkspaceId,
      'api_key': _params.apiKey,
      'client_id': _params.clientId,
      'client_secret': _params.clientSecret,
      'guid': _params.guid,
      'orchestrator_ha': _params.orchestratorHa,
      'proxy_ip': _params.proxyIp,
      'region_id': _params.regionId,
      'resource_instance': _params.resourceInstance,
      'secret': _params.secret,
      'secret_group': _params.secretGroup,
      'ssh_key_name': _params.sshKeyName,
      'standby_machine_type': _params.standbyMachineType,
      'standby_orchestrator_name': _params.standbyOrchestratorName,
      'standby_orchestrator_workspace_id': _params.standbyOrchestratorWorkspaceId,
      'standby_tier': _params.standbyTier,
      'tenant_name': _params.tenantName,
      'tier': _params.tier,
    };

    const query = {
      'stand_by_redeploy': _params.standByRedeploy,
      'accepts_incomplete': _params.acceptsIncomplete,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'createManageDr'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/manage_dr/{instance_id}',
        method: 'POST',
        body,
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drAutomationServiceInstance
   ************************/

  /**
   * View details of Last operation performed on the instance.
   *
   * Retrieves the status of the last operation performed on the specified service instance, such as provisioning,
   * updating, or deprovisioning.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceStatus>>}
   */
  public getLastOperation(
    params: DrAutomationServiceV1.GetLastOperationParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceStatus>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getLastOperation'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/last_operation/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drEvents
   ************************/

  /**
   * Get events from the cloud instance since a specific timestamp.
   *
   * Retrieves the list of events from the specified service instance ID.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.time] - (deprecated - use from_time) A time in either ISO 8601 or unix epoch format.
   * @param {string} [params.fromTime] - A from query time in either ISO 8601 or unix epoch format.
   * @param {string} [params.toTime] - A to query time in either ISO 8601 or unix epoch format.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.EventCollection>>}
   */
  public listEvents(
    params: DrAutomationServiceV1.ListEventsParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.EventCollection>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = [
      'instanceId',
      'time',
      'fromTime',
      'toTime',
      'acceptLanguage',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'time': _params.time,
      'from_time': _params.fromTime,
      'to_time': _params.toTime,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'listEvents'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/service_instances/{instance_id}/events',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get a single event.
   *
   * Retrieves the details of a specific event for the given service instance provision ID.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.eventId - Event ID.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.Event>>}
   */
  public getEvent(
    params: DrAutomationServiceV1.GetEventParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.Event>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'eventId'];
    const _validParams = ['instanceId', 'eventId', 'acceptLanguage', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
      'event_id': _params.eventId,
    };

    const sdkHeaders = getSdkHeaders(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getEvent');

    const parameters = {
      options: {
        url: '/drautomation/v1/service_instances/{instance_id}/events/{event_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
}

/*************************
 * interfaces
 ************************/

namespace DrAutomationServiceV1 {
  /** An operation response. */
  export interface Response<T = any> {
    result: T;
    status: number;
    statusText: string;
    headers: IncomingHttpHeaders;
  }

  /** The callback for a service request. */
  export type Callback<T> = (error: any, response?: Response<T>) => void;

  /** The body of a service request that returns no response data. */
  export interface EmptyObject {}

  /** A standard JS object, defined to avoid the limitations of `Object` and `object` */
  export interface JsonObject {
    [key: string]: any;
  }

  /*************************
   * request interfaces
   ************************/

  interface DefaultParams {
    headers?: OutgoingHttpHeaders;
    signal?: AbortSignal;
  }

  /** Parameters for the `updateApikey` operation. */
  export interface UpdateApikeyParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The new API key value that will replace the existing one. */
    apiKey: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
  }

  /** Parameters for the `getDrGrsLocationPair` operation. */
  export interface GetDrGrsLocationPairParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
  }

  /** Parameters for the `getDrLocations` operation. */
  export interface GetDrLocationsParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
  }

  /** Parameters for the `getDrManagedVm` operation. */
  export interface GetDrManagedVmParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
  }

  /** Parameters for the `getDrSummary` operation. */
  export interface GetDrSummaryParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
  }

  /** Parameters for the `getMachineType` operation. */
  export interface GetMachineTypeParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The primary Power virtual server workspace name. */
    primaryWorkspaceName: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** The standby Power virtual server workspace name. */
    standbyWorkspaceName?: string;
  }

  /** Parameters for the `getPowervsWorkspaces` operation. */
  export interface GetPowervsWorkspacesParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** Location ID value. */
    locationId: string;
  }

  /** Parameters for the `createManageDr` operation. */
  export interface CreateManageDrParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The location or data center identifier where the service instance is deployed. */
    locationId: string;
    /** The machine type used for deploying orchestrator. */
    machineType: string;
    /** The cloud location where your orchestator need to be created. */
    orchestratorLocationType: string;
    /** The username used for the orchestrator. */
    orchestratorName: string;
    /** The password that you can use to access your orchestrator. */
    orchestratorPassword: string;
    /** The unique identifier orchestrator workspace. */
    orchestratorWorkspaceId: string;
    /** The api Key of the service instance for deploying the disaster recovery service. */
    apiKey?: string;
    /** The Client Id created for MFA authentication API. */
    clientId?: string;
    /** The client secret created for MFA authentication API. */
    clientSecret?: string;
    /** The global unique identifier of the service instance. */
    guid?: string;
    /** Indicates whether the orchestrator High Availability (HA) is enabled for the service instance. */
    orchestratorHa?: boolean;
    /** Proxy IP for the Communication between Orchestrator and Service broker. */
    proxyIp?: string;
    /** The power virtual server region where the service instance is deployed. */
    regionId?: string;
    /** The uniquie identifier of the associated IBM Cloud resource instance. */
    resourceInstance?: string;
    /** The secret name or identifier used for retrieving credentials from secrets manager. */
    secret?: string;
    /** The secret group name in IBM Cloud Secrets Manager containing sensitive data for the service instance. */
    secretGroup?: string;
    /** The name of the SSH key used for deploying the orchestator. */
    sshKeyName?: string;
    /** The machine type used for deploying standby virtual machines. */
    standbyMachineType?: string;
    /** The username for the standby orchestrator management interface. */
    standbyOrchestratorName?: string;
    /** The unique identifier of the standby orchestrator workspace. */
    standbyOrchestratorWorkspaceId?: string;
    /** The storage tier used for deploying standby orchestrator. */
    standbyTier?: string;
    /** The tenant name for MFA authentication API. */
    tenantName?: string;
    /** The storage tier used for deploying primary orchestrator. */
    tier?: string;
    /** Flag to indicate if standby should be redeployed (must be "true" or "false"). */
    standByRedeploy?: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** A value of true indicates that both the IBM Cloud platform and the requesting client support asynchronous
     *  deprovisioning.
     */
    acceptsIncomplete?: boolean;
  }

  /** Parameters for the `getLastOperation` operation. */
  export interface GetLastOperationParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
  }

  /** Parameters for the `listEvents` operation. */
  export interface ListEventsParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** (deprecated - use from_time) A time in either ISO 8601 or unix epoch format. */
    time?: string;
    /** A from query time in either ISO 8601 or unix epoch format. */
    fromTime?: string;
    /** A to query time in either ISO 8601 or unix epoch format. */
    toTime?: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
  }

  /** Parameters for the `getEvent` operation. */
  export interface GetEventParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** Event ID. */
    eventId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
  }

  /*************************
   * model interfaces
   ************************/

  /**
   * Represents the standby DR workspace details.
   */
  export interface DRStandbyWorkspace {
    /** The detailed information of the standby DR workspace. */
    details?: DetailsDr;
    /** The unique identifier of the standby workspace. */
    id?: string;
    /** The location information of the standby workspace. */
    location?: LocationDr;
    /** The name of the standby workspace. */
    name?: string;
    /** The status of the standby workspace. */
    status?: string;
  }

  /**
   * Represents a disaster recovery workspace, including the details, location, and status.
   */
  export interface DRWorkspace {
    /** Indicates if this is the default DR workspace. */
    default?: boolean;
    /** The detailed information about the DR workspace. */
    details?: DetailsDr;
    /** The unique identifier of the DR workspace. */
    id?: string;
    /** The location information of the DR workspace. */
    location?: LocationDr;
    /** The name of the DR workspace. */
    name?: string;
    /** The status of the DR workspace. */
    status?: string;
  }

  /**
   * Details of the DR workspace.
   */
  export interface DetailsDr {
    /** Cloud Resource Name (CRN) of the DR workspace. */
    crn?: string;
  }

  /**
   * Response object containing all DR automation summary information.
   */
  export interface DrAutomationGetSummaryResponse {
    /** A flexible schema placeholder to allow any JSON value (aligns with interface{} in Go). */
    managed_vm_list: JsonObject;
    /** Contains details about the orchestrator configuration. */
    orchestrator_details: OrchestratorDetails;
    /** Contains details about the DR automation service. */
    service_details: ServiceDetails;
  }

  /**
   * The list of primary and standby disaster recovery Power virtual server workspaces.
   */
  export interface DrData {
    /** Description of Standby Workspace. */
    dr_standby_workspace_description?: any;
    /** The list of standby disaster recovery workspaces. */
    dr_standby_workspaces: DRStandbyWorkspace[];
    /** Description of Workspace. */
    dr_workspace_description?: any;
    /** The list of primary disaster recovery workspaces. */
    dr_workspaces: DRWorkspace[];
  }

  /**
   * Represents a disaster recovery location with its ID and name. .
   */
  export interface DrLocation {
    /** Unique identifier of the DR location. */
    id?: string;
    /** The name of the Power virtual server DR location . */
    name?: string;
  }

  /**
   * Represents an individual event in the system, including details about action, resource, user, and timestamps.
   */
  export interface Event {
    /** Type of action for this event. */
    action: string;
    /** Source of API when it being executed. */
    api_source?: string;
    /** ID of the Activity. */
    event_id: string;
    /** Level of the event (notice, info, warning, error). */
    level: Event.Constants.Level | string;
    /** The (translated) message of the event. */
    message: string;
    /** A flexible schema placeholder to allow any JSON value (aligns with interface{} in Go). */
    message_data?: JsonObject;
    /** A flexible schema placeholder to allow any JSON value (aligns with interface{} in Go). */
    metadata?: JsonObject;
    /** Type of resource for this event. */
    resource: string;
    /** Time of activity in ISO 8601 - RFC3339. */
    time: string;
    /** Time of activity in unix epoch. */
    timestamp: string;
    /** Information about a user associated with an event. */
    user?: EventUser;
  }
  export namespace Event {
    export namespace Constants {
      /** Level of the event (notice, info, warning, error). */
      export enum Level {
        NOTICE = 'notice',
        INFO = 'info',
        WARNING = 'warning',
        ERROR = 'error',
      }
    }
  }

  /**
   * Container object holding a list of events.
   */
  export interface EventCollection {
    /** Events. */
    events: Event[];
  }

  /**
   * Information about a user associated with an event.
   */
  export interface EventUser {
    /** Email of the User. */
    email?: string;
    /** Name of the User. */
    name?: string;
    /** ID of user who created/caused the event. */
    user_id: string;
  }

  /**
   * Response object containing a list of disaster recovery locations.
   */
  export interface GetDrLocationsResponse {
    /** List of disaster recovery locations available for the service. */
    dr_locations: DrLocation[];
  }

  /**
   * Response body containing GRS location pairs.
   */
  export interface GetGRSLocationPairResponse {
    /** A map of GRS location pairs where each key is a primary location and the value is its paired location. */
    location_pairs?: JsonObject;
  }

  /**
   * Represents a disaster recovery location.
   */
  export interface LocationDr {
    /** The region identifier of the DR location. */
    region?: string;
    /** The type of location (e.g., data-center, cloud-region). */
    type?: string;
    /** The URL endpoint to access the DR location. */
    url?: string;
  }

  /**
   * The Response body containing machine types supported by power virtual server workspace.
   */
  export interface MachineTypesByWorkspace {
    /** The Map of workspace IDs to lists of machine types. */
    workspaces?: JsonObject;
  }

  /**
   * The detailed information of a disaster recovery enabled virtual machines for the service.
   */
  export interface ManagedVmDetails {
    /** The Number of cores assigned to the managed vitual machine. */
    core?: string;
    /** The DR operation average time(in minutes) for the managed virtual machine. */
    dr_average_time?: string;
    /** The name of the region where the virtual machine is recovered. */
    dr_region?: string;
    /** The amount of memory (in GB) assigned to the managed virtual machine. */
    memory?: string;
    /** The source region where the managed virtual machine is deployed. */
    region?: string;
    /** The name of the managed virtual machine. */
    vm_name?: string;
    /** The name of the workgroup where the managed virtual machine is added for disaster recovery. */
    workgroup_name?: string;
    /** The Name of the power virtual server workspace. */
    workspace_name?: string;
  }

  /**
   * Map of VM IDs to managed VM details.
   */
  export interface ManagedVmMapResponse {
    /** A map where the key is the VM ID and the value is the corresponding ManagedVmDetails object. */
    managed_vm_list?: JsonObject;
  }

  /**
   * Contains details about the orchestrator configuration.
   */
  export interface OrchestratorDetails {
    /** The deployment time of primary orchestrator VM. */
    last_updated_orchestrator_deployment_time: string;
    /** The deployment time of StandBy orchestrator VM. */
    last_updated_standby_orchestrator_deployment_time: string;
    /** Latest Orchestrator Time in COS. */
    latest_orchestrator_time?: string;
    /** The unique identifier of location. */
    location_id: string;
    /** indicates if Multi Factor Authentication is enabled or not. */
    mfa_enabled: string;
    /** The external connectivity status of the orchestrator. */
    orch_ext_connectivity_status: string;
    /** The status of standby node addition. */
    orch_standby_node_addition_status: string;
    /** The message regarding orchestrator cluster status. */
    orchestrator_cluster_message: string;
    /** The configuration status of the orchestrator. */
    orchestrator_config_status: string;
    /** The leader node of the orchestrator group. */
    orchestrator_group_leader: string;
    /** The type of orchestrator Location. */
    orchestrator_location_type: string;
    /** The name of the primary orchestrator. */
    orchestrator_name: string;
    /** The status of the primary orchestrator. */
    orchestrator_status: string;
    /** The name of the orchestrator workspace. */
    orchestrator_workspace_name: string;
    /** The IP address of the proxy. */
    proxy_ip: string;
    /** The name of the schematic workspace. */
    schematic_workspace_name: string;
    /** The status of the schematic workspace. */
    schematic_workspace_status: string;
    /** SSH key name used for the orchestrator. */
    ssh_key_name: string;
    /** The name of the standby orchestrator. */
    standby_orchestrator_name: string;
    /** The status of the standby orchestrator. */
    standby_orchestrator_status: string;
    /** The name of the standby orchestrator workspace. */
    standby_orchestrator_workspace_name: string;
    /** The name of the transit gateway. */
    transit_gateway_name: string;
    /** The name of the VPC. */
    vpc_name: string;
  }

  /**
   * Contains details about the DR automation service.
   */
  export interface ServiceDetails {
    /** The deployment crn. */
    crn: string;
    /** The name of the deployment. */
    deployment_name: string;
    /** The Service description. */
    description: string;
    /** The flag indicating whether orchestartor HA is enabled. */
    orchestrator_ha: boolean;
    /** The plan name. */
    plan_name: string;
    /** The service Orchestator primary IP address. */
    primary_ip_address: string;
    /** The Primary Orchestrator Dashboard URL. */
    primary_orchestrator_dashboard_url: string;
    /** The disaster recovery location. */
    recovery_location: string;
    /** The Resource group name. */
    resource_group: string;
    /** The standby orchestrator current status details. */
    standby_description: string;
    /** The service Orchestator standby IP address. */
    standby_ip_address: string;
    /** The Standby Orchestrator Dashboard URL. */
    standby_orchestrator_dashboard_url: string;
    /** The standby orchestrator current status. */
    standby_status: string;
    /** The Status of the service. */
    status: string;
  }

  /**
   * Represents the response details for managing a DR service instance.
   */
  export interface ServiceInstanceManageDR {
    /** URL to the dashboard for managing the DR service instance in IBM Cloud. */
    dashboard_url?: string;
    /** The CRN (Cloud Resource Name) of the DR service instance. */
    id?: string;
  }

  /**
   * Represents the current status and details of a service instance including orchestrator state, networking, and
   * recovery information.
   */
  export interface ServiceInstanceStatus {
    /** The service instance crn. */
    crn: string;
    /** The name of the service instance deployment. */
    deployment_name: string;
    /** The deployment time of primary orchestrator VM. */
    last_updated_orchestrator_deployment_time: string;
    /** The deployment time of StandBy orchestrator VM. */
    last_updated_standby_orchestrator_deployment_time: string;
    /** Indicated whether multi factor authentication is ennabled or not. */
    mfa_enabled: string;
    /** Status of standby node addition to the orchestrator cluster. */
    orch_ext_connectivity_status?: string;
    /** The status of standby node in the Orchestrator cluster. */
    orch_standby_node_addtion_status: string;
    /** The current status of the primary orchestrator VM. */
    orchestrator_cluster_message: string;
    /** The configuration status of the orchestrator cluster. */
    orchestrator_config_status: string;
    /** Indicates whether high availability (HA) is enabled for the orchestrator. */
    orchestrator_ha: boolean;
    /** The name of the DR Automation plan. */
    plan_name: string;
    /** Indicates the progress details of primary orchestrator creation. */
    primary_description: string;
    /** The IP address of the primary orchestrator VM. */
    primary_ip_address: string;
    /** The configuration status of the orchestrator cluster. */
    primary_orchestrator_status: string;
    /** The disaster recovery location associated with the instance. */
    recovery_location: string;
    /** The resource group to which the service instance belongs. */
    resource_group: string;
    /** Indicates the progress details of primary orchestrator creation. */
    standby_description: string;
    /** The IP address of the standby orchestrator VM. */
    standby_ip_address: string;
    /** The current state of the standby orchestrator. */
    standby_status: string;
    /** The current state of the primary orchestrator. */
    status: string;
  }

  /**
   * Response object for API key validation, including ID, status, and description.
   */
  export interface ValidationKeyResponse {
    /** Validation result message. */
    description?: string;
    /** Unique identifier of the API key. */
    id?: string;
    /** Status of the API key. */
    status?: string;
  }
}

export = DrAutomationServiceV1;
