/**
 * (C) Copyright IBM Corp. 2025.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * IBM OpenAPI SDK Code Generator Version: 3.105.0-3c13b041-20250605-193116
 */

import * as extend from 'extend';
import { IncomingHttpHeaders, OutgoingHttpHeaders } from 'http';
import {
  AbortSignal,
  Authenticator,
  BaseService,
  UserOptions,
  getAuthenticatorFromEnvironment,
  validateParams,
} from 'ibm-cloud-sdk-core';
import { getSdkHeaders } from '../lib/common';

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 1.0.0
 */

class DrAutomationServiceV1 extends BaseService {
  static DEFAULT_SERVICE_URL: string = 'https://power-dra.test.cloud.ibm.com/drautomation/v1';

  static DEFAULT_SERVICE_NAME: string = 'dr_automation_service';

  /*************************
   * Factory method
   ************************/

  /**
   * Constructs an instance of DrAutomationServiceV1 with passed in options and external configuration.
   *
   * @param {UserOptions} [options] - The parameters to send to the service.
   * @param {string} [options.serviceName] - The name of the service to configure
   * @param {Authenticator} [options.authenticator] - The Authenticator object used to authenticate requests to the service
   * @param {string} [options.serviceUrl] - The base URL for the service
   * @returns {DrAutomationServiceV1}
   */

  public static newInstance(options: UserOptions): DrAutomationServiceV1 {
    options = options || {};

    if (!options.serviceName) {
      options.serviceName = this.DEFAULT_SERVICE_NAME;
    }
    if (!options.authenticator) {
      options.authenticator = getAuthenticatorFromEnvironment(options.serviceName);
    }
    const service = new DrAutomationServiceV1(options);
    service.configureService(options.serviceName);
    if (options.serviceUrl) {
      service.setServiceUrl(options.serviceUrl);
    }
    return service;
  }

  /**
   * Construct a DrAutomationServiceV1 object.
   *
   * @param {Object} options - Options for the service.
   * @param {string} [options.serviceUrl] - The base URL for the service
   * @param {OutgoingHttpHeaders} [options.headers] - Default headers that shall be included with every request to the service.
   * @param {Authenticator} options.authenticator - The Authenticator object used to authenticate requests to the service
   * @constructor
   * @returns {DrAutomationServiceV1}
   */
  constructor(options: UserOptions) {
    options = options || {};

    super(options);
    if (options.serviceUrl) {
      this.setServiceUrl(options.serviceUrl);
    } else {
      this.setServiceUrl(DrAutomationServiceV1.DEFAULT_SERVICE_URL);
    }
  }

  /*************************
   * drAutomationConfig
   ************************/

  /**
   * Updates the API key for the specified service instance.
   *
   * Updating the current API key details for the specified service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.apiKey - The new API key value that will replace the existing one.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>>}
   */
  public updateApikey(
    params: DrAutomationServiceV1.UpdateApikeyParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'apiKey'];
    const _validParams = [
      'instanceId',
      'apiKey',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'api_key': _params.apiKey,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'updateApikey'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/apikey/{instance_id}',
        method: 'PUT',
        body,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get GRS location pairs by instance ID.
   *
   * Retrieves the (GRS) location pairs associated with the specified service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetGRSLocationPairResponse>>}
   */
  public getDrGrsLocationPair(
    params: DrAutomationServiceV1.GetDrGrsLocationPairParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetGRSLocationPairResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getDrGrsLocationPair'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_grs_location_pairs/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get Disaster recovery locations.
   *
   * Retrieves the list of disaster recovery (DR) locations available for the specified service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetDrLocationsResponse>>}
   */
  public getDrLocations(
    params: DrAutomationServiceV1.GetDrLocationsParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetDrLocationsResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getDrLocations'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_locations/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get managed VMs by instance ID.
   *
   * Retrieves the list of disaster recovery (DR) managed virtual machines for the specified service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ManagedVmMapResponse>>}
   */
  public getDrManagedVm(
    params: DrAutomationServiceV1.GetDrManagedVmParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ManagedVmMapResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getDrManagedVm'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_managed_vms/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Disaster Recovery deployment details.
   *
   * Retrieves the disaster recovery (DR) summary details for the specified service instance, including key
   * configuration and status information.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrAutomationGetSummaryResponse>>}
   */
  public getDrSummary(
    params: DrAutomationServiceV1.GetDrSummaryParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrAutomationGetSummaryResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getDrSummary'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_summary/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drAutomationIbmCloud
   ************************/

  /**
   * Get MachineTypes by Instance Id.
   *
   * Retrieves the list of supported machine types for the given service instance ID. This endpoint is used to identify
   * machine types available for disaster recovery automation.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.primaryWorkspaceName - Primary Workspace Name.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {string} [params.standbyWorkspaceName] - Standby Workspace Name.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.MachineTypesByWorkspace>>}
   */
  public getMachineType(
    params: DrAutomationServiceV1.GetMachineTypeParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.MachineTypesByWorkspace>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'primaryWorkspaceName'];
    const _validParams = [
      'instanceId',
      'primaryWorkspaceName',
      'acceptLanguage',
      'ifNoneMatch',
      'standbyWorkspaceName',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'primary_workspace_name': _params.primaryWorkspaceName,
      'standby_workspace_name': _params.standbyWorkspaceName,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getMachineType'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/machinetypes/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * List of schematic workspaces.
   *
   * Retrieves the list of schematics workspaces associated with the specified disaster recovery service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.SchematicWorkspacesResponse>>}
   */
  public getSchematicWorkspace(
    params: DrAutomationServiceV1.GetSchematicWorkspaceParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.SchematicWorkspacesResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getSchematicWorkspace'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/schematics_workspaces/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * List of primary and standby powervs workspaces for custom vpc.
   *
   * Retrieves the details of the specified custom VPC workspace for a disaster recovery service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.locationId - Location ID value.
   * @param {string} params.vpcId - vpc id value.
   * @param {string} params.tgId - transit gateway id value.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrDataCustomVPC>>}
   */
  public getPowervsWorkspacesForCustomVpc(
    params: DrAutomationServiceV1.GetPowervsWorkspacesForCustomVpcParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrDataCustomVPC>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'locationId', 'vpcId', 'tgId'];
    const _validParams = [
      'instanceId',
      'locationId',
      'vpcId',
      'tgId',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'location_id': _params.locationId,
      'vpc_id': _params.vpcId,
      'tg_id': _params.tgId,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getPowervsWorkspacesForCustomVpc'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/workspaces_custom_vpc/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * List of primary and standby powervs workspaces for schematic workspace.
   *
   * Retrieves the details of the specified workspace schematic for a disaster recovery service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.schematicId - Schematic ID value.
   * @param {string} params.locationId - Location ID value.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrData>>}
   */
  public getPvsworkspaceSchematic(
    params: DrAutomationServiceV1.GetPvsworkspaceSchematicParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrData>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'schematicId', 'locationId'];
    const _validParams = [
      'instanceId',
      'schematicId',
      'locationId',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'schematic_id': _params.schematicId,
      'location_id': _params.locationId,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getPvsworkspaceSchematic'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/workspaces_schematic/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drAutomationManageDr
   ************************/

  /**
   * View configured DR automation details.
   *
   * Retrieves the (DR) management configuration and status for the specified service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>>}
   */
  public getManageDr(
    params: DrAutomationServiceV1.GetManageDrParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getManageDr'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/manage_dr/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Configure DR automation.
   *
   * Initiates or updates the disaster recovery (DR) management workflow for the specified service instance. Use this
   * API to configure DR automation.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.action] - to proceed with async operation if all the config details are updated to DB.
   * @param {string} [params.apiKey] - api Key of the service instance.
   * @param {string} [params.guid] - Global unique identifier of the service instance.
   * @param {string} [params.locationId] - Location or data center identifier where the service instance is deployed.
   * @param {string} [params.machineType] - Machine type or flavor used for virtual machines in the service instance.
   * @param {boolean} [params.orchestratorHa] - Flag to enable or disable High Availability (HA) for the service
   * instance.
   * @param {string} [params.orchestratorLocationType] - Type of orchestrator cluster used in the service instance.
   * @param {string} [params.orchestratorName] - Username for the orchestrator management interface.
   * @param {string} [params.orchestratorPassword] - Password for the orchestrator management interface.
   * @param {string} [params.orchestratorWorkspaceId] - ID of the orchestrator workspace.
   * @param {string} [params.orchestratorWorkspaceLocation] - Location of the orchestrator workspace.
   * @param {string} [params.proxyIp] - Proxy IP address used by the service instance for communication.
   * @param {string} [params.regionId] - Cloud region where the service instance is deployed.
   * @param {string} [params.resourceInstance] - ID of the associated IBM Cloud resource instance.
   * @param {string} [params.schematicWorkspaceId] - ID of the IBM Cloud Schematics workspace linked to the service
   * instance.
   * @param {string} [params.secondaryWorkspaceId] - ID of the secondary workspace used for redundancy or disaster
   * recovery.
   * @param {string} [params.secret] - Secret name or identifier used for retrieving credentials from Secrets Manager.
   * @param {string} [params.secretGroup] - Secret group name in IBM Cloud Secrets Manager containing sensitive data for
   * the service instance.
   * @param {string} [params.sshKeyName] - Name of the SSH key stored in the cloud provider.
   * @param {string} [params.sshPublicKey] - SSH public key for accessing virtual machines in the service instance.
   * @param {string} [params.standbyMachineType] - Machine type or flavor used for standby virtual machines.
   * @param {string} [params.standbyOrchestratorName] - Username for the standby orchestrator management interface.
   * @param {string} [params.standbyOrchestratorWorkspaceId] - ID of the standby orchestrator workspace.
   * @param {string} [params.standbyOrchestratorWorkspaceLocation] - Location of the standby orchestrator workspace.
   * @param {string} [params.standbySchematicWorkspaceId] - ID of the standby IBM Cloud Schematics workspace.
   * @param {string} [params.standbyTier] - Tier of the standby service instance.
   * @param {string} [params.tier] - Tier of the service instance (e.g., Standard, Premium).
   * @param {string} [params.transitGatewayId] - ID of the transit gateway used for interconnecting networks.
   * @param {string} [params.vpcId] - ID of the Virtual Private Cloud (VPC) associated with the service instance.
   * @param {string} [params.standByRedeploy] - Flag to indicate if standby should be redeployed (must be "true" or
   * "false").
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {boolean} [params.acceptsIncomplete] - A value of true indicates that both the IBM Cloud platform and the
   * requesting client support asynchronous deprovisioning.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>>}
   */
  public createManageDr(
    params: DrAutomationServiceV1.CreateManageDrParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = [
      'instanceId',
      'action',
      'apiKey',
      'guid',
      'locationId',
      'machineType',
      'orchestratorHa',
      'orchestratorLocationType',
      'orchestratorName',
      'orchestratorPassword',
      'orchestratorWorkspaceId',
      'orchestratorWorkspaceLocation',
      'proxyIp',
      'regionId',
      'resourceInstance',
      'schematicWorkspaceId',
      'secondaryWorkspaceId',
      'secret',
      'secretGroup',
      'sshKeyName',
      'sshPublicKey',
      'standbyMachineType',
      'standbyOrchestratorName',
      'standbyOrchestratorWorkspaceId',
      'standbyOrchestratorWorkspaceLocation',
      'standbySchematicWorkspaceId',
      'standbyTier',
      'tier',
      'transitGatewayId',
      'vpcId',
      'standByRedeploy',
      'acceptLanguage',
      'ifNoneMatch',
      'acceptsIncomplete',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'action': _params.action,
      'api_key': _params.apiKey,
      'guid': _params.guid,
      'location_id': _params.locationId,
      'machine_type': _params.machineType,
      'orchestrator_ha': _params.orchestratorHa,
      'orchestrator_location_type': _params.orchestratorLocationType,
      'orchestrator_name': _params.orchestratorName,
      'orchestrator_password': _params.orchestratorPassword,
      'orchestrator_workspace_id': _params.orchestratorWorkspaceId,
      'orchestrator_workspace_location': _params.orchestratorWorkspaceLocation,
      'proxy_ip': _params.proxyIp,
      'region_id': _params.regionId,
      'resource_instance': _params.resourceInstance,
      'schematic_workspace_id': _params.schematicWorkspaceId,
      'secondary_workspace_id': _params.secondaryWorkspaceId,
      'secret': _params.secret,
      'secret_group': _params.secretGroup,
      'ssh_key_name': _params.sshKeyName,
      'ssh_public_key': _params.sshPublicKey,
      'standby_machine_type': _params.standbyMachineType,
      'standby_orchestrator_name': _params.standbyOrchestratorName,
      'standby_orchestrator_workspace_id': _params.standbyOrchestratorWorkspaceId,
      'standby_orchestrator_workspace_location': _params.standbyOrchestratorWorkspaceLocation,
      'standby_schematic_workspace_id': _params.standbySchematicWorkspaceId,
      'standby_tier': _params.standbyTier,
      'tier': _params.tier,
      'transit_gateway_id': _params.transitGatewayId,
      'vpc_id': _params.vpcId,
    };

    const query = {
      'stand_by_redeploy': _params.standByRedeploy,
      'accepts_incomplete': _params.acceptsIncomplete,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'createManageDr'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/manage_dr/{instance_id}',
        method: 'POST',
        body,
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drAutomationServiceInstance
   ************************/

  /**
   * View details of Last operation performed on the instance id.
   *
   * Retrieves the status of the last operation performed on the specified service instance, such as provisioning,
   * updating, or deprovisioning.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceStatus>>}
   */
  public getLastOperation(
    params: DrAutomationServiceV1.GetLastOperationParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceStatus>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getLastOperation'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/last_operation/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drEvents
   ************************/

  /**
   * Get events from this cloud instance since a specific timestamp.
   *
   * Retrieves the list of events for the specified service instance provision ID.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.provisionId - provision id.
   * @param {string} [params.time] - (deprecated - use from_time) A time in either ISO 8601 or unix epoch format.
   * @param {string} [params.fromTime] - A from query time in either ISO 8601 or unix epoch format.
   * @param {string} [params.toTime] - A to query time in either ISO 8601 or unix epoch format.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.EventCollection>>}
   */
  public listEvents(
    params: DrAutomationServiceV1.ListEventsParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.EventCollection>> {
    const _params = { ...params };
    const _requiredParams = ['provisionId'];
    const _validParams = [
      'provisionId',
      'time',
      'fromTime',
      'toTime',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'time': _params.time,
      'from_time': _params.fromTime,
      'to_time': _params.toTime,
    };

    const path = {
      'provision_id': _params.provisionId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'listEvents'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/service_instances/{provision_id}/events',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get a single event.
   *
   * Retrieves the details of a specific event for the given service instance provision ID.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.provisionId - provision id.
   * @param {string} params.eventId - Event ID.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.Event>>}
   */
  public getEvent(
    params: DrAutomationServiceV1.GetEventParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.Event>> {
    const _params = { ...params };
    const _requiredParams = ['provisionId', 'eventId'];
    const _validParams = [
      'provisionId',
      'eventId',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'provision_id': _params.provisionId,
      'event_id': _params.eventId,
    };

    const sdkHeaders = getSdkHeaders(DrAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getEvent');

    const parameters = {
      options: {
        url: '/drautomation/v1/service_instances/{provision_id}/events/{event_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
}

/*************************
 * interfaces
 ************************/

namespace DrAutomationServiceV1 {
  /** An operation response. */
  export interface Response<T = any> {
    result: T;
    status: number;
    statusText: string;
    headers: IncomingHttpHeaders;
  }

  /** The callback for a service request. */
  export type Callback<T> = (error: any, response?: Response<T>) => void;

  /** The body of a service request that returns no response data. */
  export interface EmptyObject {}

  /** A standard JS object, defined to avoid the limitations of `Object` and `object` */
  export interface JsonObject {
    [key: string]: any;
  }

  /*************************
   * request interfaces
   ************************/

  interface DefaultParams {
    headers?: OutgoingHttpHeaders;
    signal?: AbortSignal;
  }

  /** Parameters for the `updateApikey` operation. */
  export interface UpdateApikeyParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The new API key value that will replace the existing one. */
    apiKey: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getDrGrsLocationPair` operation. */
  export interface GetDrGrsLocationPairParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getDrLocations` operation. */
  export interface GetDrLocationsParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getDrManagedVm` operation. */
  export interface GetDrManagedVmParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getDrSummary` operation. */
  export interface GetDrSummaryParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getMachineType` operation. */
  export interface GetMachineTypeParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** Primary Workspace Name. */
    primaryWorkspaceName: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
    /** Standby Workspace Name. */
    standbyWorkspaceName?: string;
  }

  /** Parameters for the `getSchematicWorkspace` operation. */
  export interface GetSchematicWorkspaceParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getPowervsWorkspacesForCustomVpc` operation. */
  export interface GetPowervsWorkspacesForCustomVpcParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** Location ID value. */
    locationId: string;
    /** vpc id value. */
    vpcId: string;
    /** transit gateway id value. */
    tgId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getPvsworkspaceSchematic` operation. */
  export interface GetPvsworkspaceSchematicParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** Schematic ID value. */
    schematicId: string;
    /** Location ID value. */
    locationId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getManageDr` operation. */
  export interface GetManageDrParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `createManageDr` operation. */
  export interface CreateManageDrParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** to proceed with async operation if all the config details are updated to DB. */
    action?: string;
    /** api Key of the service instance. */
    apiKey?: string;
    /** Global unique identifier of the service instance. */
    guid?: string;
    /** Location or data center identifier where the service instance is deployed. */
    locationId?: string;
    /** Machine type or flavor used for virtual machines in the service instance. */
    machineType?: string;
    /** Flag to enable or disable High Availability (HA) for the service instance. */
    orchestratorHa?: boolean;
    /** Type of orchestrator cluster used in the service instance. */
    orchestratorLocationType?: string;
    /** Username for the orchestrator management interface. */
    orchestratorName?: string;
    /** Password for the orchestrator management interface. */
    orchestratorPassword?: string;
    /** ID of the orchestrator workspace. */
    orchestratorWorkspaceId?: string;
    /** Location of the orchestrator workspace. */
    orchestratorWorkspaceLocation?: string;
    /** Proxy IP address used by the service instance for communication. */
    proxyIp?: string;
    /** Cloud region where the service instance is deployed. */
    regionId?: string;
    /** ID of the associated IBM Cloud resource instance. */
    resourceInstance?: string;
    /** ID of the IBM Cloud Schematics workspace linked to the service instance. */
    schematicWorkspaceId?: string;
    /** ID of the secondary workspace used for redundancy or disaster recovery. */
    secondaryWorkspaceId?: string;
    /** Secret name or identifier used for retrieving credentials from Secrets Manager. */
    secret?: string;
    /** Secret group name in IBM Cloud Secrets Manager containing sensitive data for the service instance. */
    secretGroup?: string;
    /** Name of the SSH key stored in the cloud provider. */
    sshKeyName?: string;
    /** SSH public key for accessing virtual machines in the service instance. */
    sshPublicKey?: string;
    /** Machine type or flavor used for standby virtual machines. */
    standbyMachineType?: string;
    /** Username for the standby orchestrator management interface. */
    standbyOrchestratorName?: string;
    /** ID of the standby orchestrator workspace. */
    standbyOrchestratorWorkspaceId?: string;
    /** Location of the standby orchestrator workspace. */
    standbyOrchestratorWorkspaceLocation?: string;
    /** ID of the standby IBM Cloud Schematics workspace. */
    standbySchematicWorkspaceId?: string;
    /** Tier of the standby service instance. */
    standbyTier?: string;
    /** Tier of the service instance (e.g., Standard, Premium). */
    tier?: string;
    /** ID of the transit gateway used for interconnecting networks. */
    transitGatewayId?: string;
    /** ID of the Virtual Private Cloud (VPC) associated with the service instance. */
    vpcId?: string;
    /** Flag to indicate if standby should be redeployed (must be "true" or "false"). */
    standByRedeploy?: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
    /** A value of true indicates that both the IBM Cloud platform and the requesting client support asynchronous
     *  deprovisioning.
     */
    acceptsIncomplete?: boolean;
  }

  /** Parameters for the `getLastOperation` operation. */
  export interface GetLastOperationParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `listEvents` operation. */
  export interface ListEventsParams extends DefaultParams {
    /** provision id. */
    provisionId: string;
    /** (deprecated - use from_time) A time in either ISO 8601 or unix epoch format. */
    time?: string;
    /** A from query time in either ISO 8601 or unix epoch format. */
    fromTime?: string;
    /** A to query time in either ISO 8601 or unix epoch format. */
    toTime?: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getEvent` operation. */
  export interface GetEventParams extends DefaultParams {
    /** provision id. */
    provisionId: string;
    /** Event ID. */
    eventId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /*************************
   * model interfaces
   ************************/

  /**
   * Represents the standby DR workspace details.
   */
  export interface DRStandbyWorkspace {
    /** Detailed information of the standby DR workspace. */
    details?: DetailsDr;
    /** Unique identifier of the standby workspace. */
    id?: string;
    /** Location information of the standby workspace. */
    location?: LocationDr;
    /** Name of the standby workspace. */
    name?: string;
    /** Current status of the standby workspace. */
    status?: string;
  }

  /**
   * Represents a disaster recovery workspace, including its details, location, and status.
   */
  export interface DRWorkspace {
    /** Indicates if this is the default DR workspace. */
    default?: boolean;
    /** Detailed information about the DR workspace. */
    details?: DetailsDr;
    /** Unique identifier of the DR workspace. */
    id?: string;
    /** Location information of the DR workspace. */
    location?: LocationDr;
    /** Name of the DR workspace. */
    name?: string;
    /** Current status of the DR workspace. */
    status?: string;
  }

  /**
   * Details of the DR workspace.
   */
  export interface DetailsDr {
    /** Cloud Resource Name (CRN) of the DR workspace. */
    crn?: string;
  }

  /**
   * Reference to a catalog item associated with the DR automation workspace.
   */
  export interface DrAutomationCatalogRef {
    /** Name of the catalog item that defines the resource or configuration. */
    item_name?: string;
  }

  /**
   * Response object containing all DR automation summary information.
   */
  export interface DrAutomationGetSummaryResponse {
    /** A flexible schema placeholder to allow any JSON value (aligns with interface{} in Go). */
    managed_vm_list: JsonObject;
    /** Contains details about the orchestrator configuration. */
    orchestrator_details: OrchestratorDetails;
    /** Contains details about the DR automation service. */
    service_details: ServiceDetails;
  }

  /**
   * Represents a Schematics workspace configuration used for DR automation.
   */
  export interface DrAutomationSchematicsWorkspace {
    /** Reference to a catalog item associated with the DR automation workspace. */
    catalog_ref?: DrAutomationCatalogRef;
    /** Timestamp when the Schematics workspace was created, in ISO 8601 format (UTC). */
    created_at?: string;
    /** CRN of the user or service that created the Schematics workspace. */
    created_by?: string;
    /** Cloud Resource Name (CRN) of the Schematics workspace. */
    crn?: string;
    /** Detailed description of the Schematics workspace. */
    description?: string;
    /** Unique identifier of the Schematics workspace. */
    id?: string;
    /** Region where the Schematics workspace is hosted. */
    location?: string;
    /** Human-readable name of the Schematics workspace. */
    name?: string;
    /** Current lifecycle status of the Schematics workspace. */
    status?: string;
  }

  /**
   * Contains the list of primary and standby DR workspaces.
   */
  export interface DrData {
    /** Description of Standby Workspace. */
    dr_standby_workspace_description?: any;
    /** List of standby disaster recovery workspaces. */
    dr_standby_workspaces: DRStandbyWorkspace[];
    /** Description of Workspace. */
    dr_workspace_description?: any;
    /** List of primary disaster recovery workspaces. */
    dr_workspaces: DRWorkspace[];
  }

  /**
   * Contains the list of primary and standby DR workspaces.
   */
  export interface DrDataCustomVPC {
    /** List of standby disaster recovery workspaces. */
    dr_standby_workspaces: DRStandbyWorkspace[];
    /** List of primary disaster recovery workspaces. */
    dr_workspaces: DRWorkspace[];
  }

  /**
   * Represents a disaster recovery location with its ID and name.
   */
  export interface DrLocation {
    /** Unique identifier of the DR location. */
    id?: string;
    /** Name of the DR location. */
    name?: string;
  }

  /**
   * Represents an individual event in the system, including details about action, resource, user, and timestamps.
   */
  export interface Event {
    /** Type of action for this event. */
    action: string;
    /** Source of API when it being executed. */
    api_source?: string;
    /** ID of the Activity. */
    event_id: string;
    /** Level of the event (notice, info, warning, error). */
    level: Event.Constants.Level | string;
    /** The (translated) message of the event. */
    message: string;
    /** A flexible schema placeholder to allow any JSON value (aligns with interface{} in Go). */
    message_data?: JsonObject;
    /** A flexible schema placeholder to allow any JSON value (aligns with interface{} in Go). */
    metadata?: JsonObject;
    /** Type of resource for this event. */
    resource: string;
    /** Time of activity in ISO 8601 - RFC3339. */
    time: string;
    /** Time of activity in unix epoch. */
    timestamp: string;
    /** Information about a user associated with an event. */
    user?: EventUser;
  }
  export namespace Event {
    export namespace Constants {
      /** Level of the event (notice, info, warning, error). */
      export enum Level {
        NOTICE = 'notice',
        INFO = 'info',
        WARNING = 'warning',
        ERROR = 'error',
      }
    }
  }

  /**
   * Container object holding a list of events.
   */
  export interface EventCollection {
    /** Events. */
    event: Event[];
  }

  /**
   * Information about a user associated with an event.
   */
  export interface EventUser {
    /** Email of the User. */
    email?: string;
    /** Name of the User. */
    name?: string;
    /** ID of user who created/caused the event. */
    user_id: string;
  }

  /**
   * Response object containing a list of disaster recovery locations.
   */
  export interface GetDrLocationsResponse {
    /** List of disaster recovery locations available for the service. */
    dr_locations: DrLocation[];
  }

  /**
   * Response body containing GRS location pairs.
   */
  export interface GetGRSLocationPairResponse {
    /** A map of GRS location pairs where each key is a primary location and the value is its paired location. */
    location_pairs?: JsonObject;
  }

  /**
   * Represents a disaster recovery location.
   */
  export interface LocationDr {
    /** The region identifier of the DR location. */
    region?: string;
    /** The type of location (e.g., data-center, cloud-region). */
    type?: string;
    /** The URL endpoint to access the DR location. */
    url?: string;
  }

  /**
   * Response body containing machine types grouped by workspace.
   */
  export interface MachineTypesByWorkspace {
    /** Map of workspace IDs to lists of machine types. */
    workspaces?: JsonObject;
  }

  /**
   * Detailed information of a managed virtual machine.
   */
  export interface ManagedVmDetails {
    /** Number of CPU cores allocated to the managed VM. */
    core?: string;
    /** Average DR operation time in minutes for this VM. */
    dr_average_time?: string;
    /** Target region for disaster recovery. */
    dr_region?: string;
    /** Amount of memory (in GB) allocated to the VM. */
    memory?: string;
    /** Primary region where the VM is deployed. */
    region?: string;
    /** Name of the managed virtual machine. */
    vm_name?: string;
    /** Name of the workgroup to which this VM belongs. */
    workgroup_name?: string;
    /** Name of the workspace where the VM resides. */
    workspace_name?: string;
  }

  /**
   * Map of VM IDs to managed VM details.
   */
  export interface ManagedVmMapResponse {
    /** A map where the key is the VM ID and the value is the corresponding ManagedVmDetails object. */
    managed_vms?: JsonObject;
  }

  /**
   * Contains details about the orchestrator configuration.
   */
  export interface OrchestratorDetails {
    /** Deployment time of primary orchestrator VM. */
    last_updated_orchestrator_deployment_time: string;
    /** Deployment time of StandBy orchestrator VM. */
    last_updated_standby_orchestrator_deployment_time: string;
    /** Location identifier. */
    location_id: string;
    /** External connectivity status of the orchestrator. */
    orch_ext_connectivity_status: string;
    /** Status of standby node addition. */
    orch_standby_node_addition_status: string;
    /** Message regarding orchestrator cluster status. */
    orchestrator_cluster_message: string;
    /** Configuration status of the orchestrator. */
    orchestrator_config_status: string;
    /** Leader node of the orchestrator group. */
    orchestrator_group_leader: string;
    /** Type of orchestrator Location. */
    orchestrator_location_type: string;
    /** Name of the primary orchestrator. */
    orchestrator_name: string;
    /** Status of the primary orchestrator. */
    orchestrator_status: string;
    /** Name of the orchestrator workspace. */
    orchestrator_workspace_name: string;
    /** IP address of the proxy. */
    proxy_ip: string;
    /** Name of the schematic workspace. */
    schematic_workspace_name: string;
    /** Status of the schematic workspace. */
    schematic_workspace_status: string;
    /** SSH key name used for the orchestrator. */
    ssh_key_name: string;
    /** Name of the standby orchestrator. */
    standby_orchestrator_name: string;
    /** Status of the standby orchestrator. */
    standby_orchestrator_status: string;
    /** Name of the standby orchestrator workspace. */
    standby_orchestrator_workspace_name: string;
    /** Name of the transit gateway. */
    transit_gateway_name: string;
    /** Name of the VPC. */
    vpc_name: string;
  }

  /**
   * Response object containing the list of Schematics workspaces.
   */
  export interface SchematicWorkspacesResponse {
    /** List of Schematics workspaces associated with the DR automation service instance. */
    workspaces: DrAutomationSchematicsWorkspace[];
  }

  /**
   * Contains details about the DR automation service.
   */
  export interface ServiceDetails {
    /** Cloud Resource Name identifier. */
    crn: string;
    /** Name of the deployment. */
    deployment_name: string;
    /** Description of the primary service. */
    description: string;
    /** Flag indicating if KSYS HA is enabled. */
    is_ksys_ha: boolean;
    /** plan name. */
    plan_name: string;
    /** IP address of the primary service. */
    primary_ip_address: string;
    /** Primary Orchestrator Dashboard URL. */
    primary_orchestrator_dashboard_url: string;
    /** Location for disaster recovery. */
    recovery_location: string;
    /** Resource group name. */
    resource_group: string;
    /** Description of the standby service. */
    standby_description: string;
    /** IP address of the standby service. */
    standby_ip_address: string;
    /** Standby Orchestrator Dashboard URL. */
    standby_orchestrator_dashboard_url: string;
    /** Current status of the standby service. */
    standby_status: string;
    /** Current status of the primary service. */
    status: string;
  }

  /**
   * Represents the response details for managing a DR service instance.
   */
  export interface ServiceInstanceManageDR {
    /** URL to the dashboard for managing the DR service instance in IBM Cloud. */
    dashboard_url?: string;
    /** The CRN (Cloud Resource Name) of the DR service instance. */
    id?: string;
  }

  /**
   * Represents the current status and details of a service instance including orchestrator state, networking, and
   * recovery information.
   */
  export interface ServiceInstanceStatus {
    /** Cloud Resource Name (CRN) of the service instance. */
    crn: string;
    /** Name of the service instance deployment. */
    deployment_name: string;
    /** Indicates whether high availability (HA) is enabled for the orchestrator. */
    is_ksys_ha: boolean;
    /** Deployment time of primary orchestrator VM. */
    last_updated_orchestrator_deployment_time: string;
    /** Deployment time of StandBy orchestrator VM. */
    last_updated_standby_orchestrator_deployment_time: string;
    /** Status of standby node addition to the orchestrator cluster. */
    orch_ext_connectivity_status?: string;
    /** Health or informational message about the orchestrator cluster. */
    orch_standby_node_addtion_status: string;
    /** Current status of the primary orchestrator VM. */
    orchestrator_cluster_message: string;
    /** Configuration status of the orchestrator cluster. */
    orchestrator_config_status: string;
    /** Name of the Plan. */
    plan_name: string;
    /** Detailed status message for the primary orchestrator VM. */
    primary_description: string;
    /** IP address of the primary orchestrator VM. */
    primary_ip_address: string;
    /** Configuration status of the orchestrator cluster. */
    primary_orchestrator_status: string;
    /** Disaster recovery location associated with the instance. */
    recovery_location: string;
    /** Resource group to which the service instance belongs. */
    resource_group: string;
    /** Detailed status message for the standby orchestrator VM. */
    standby_description: string;
    /** IP address of the standby orchestrator VM. */
    standby_ip_address: string;
    /** Current state of the standby orchestrator VM. */
    standby_status: string;
    /** Overall status of the service instance. */
    status: string;
  }

  /**
   * Response object for API key validation, including ID, status, and description.
   */
  export interface ValidationKeyResponse {
    /** Validation result message. */
    description?: string;
    /** Unique identifier of the API key. */
    id?: string;
    /** Status of the API key. */
    status?: string;
  }
}

export = DrAutomationServiceV1;
