/**
 * (C) Copyright IBM Corp. 2025.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * IBM OpenAPI SDK Code Generator Version: 3.105.0-3c13b041-20250605-193116
 */

import * as extend from 'extend';
import { IncomingHttpHeaders, OutgoingHttpHeaders } from 'http';
import {
  AbortSignal,
  Authenticator,
  BaseService,
  UserOptions,
  getAuthenticatorFromEnvironment,
  validateParams,
} from 'ibm-cloud-sdk-core';
import { getSdkHeaders } from '../lib/common';

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 1.0.0
 */

class DrAutomationServiceV1 extends BaseService {
  static DEFAULT_SERVICE_URL: string = 'https://power-dra.test.cloud.ibm.com/drautomation/v1';

  static DEFAULT_SERVICE_NAME: string = 'dr_automation_service';

  /*************************
   * Factory method
   ************************/

  /**
   * Constructs an instance of DrAutomationServiceV1 with passed in options and external configuration.
   *
   * @param {UserOptions} [options] - The parameters to send to the service.
   * @param {string} [options.serviceName] - The name of the service to configure
   * @param {Authenticator} [options.authenticator] - The Authenticator object used to authenticate requests to the service
   * @param {string} [options.serviceUrl] - The base URL for the service
   * @returns {DrAutomationServiceV1}
   */

  public static newInstance(options: UserOptions): DrAutomationServiceV1 {
    options = options || {};

    if (!options.serviceName) {
      options.serviceName = this.DEFAULT_SERVICE_NAME;
    }
    if (!options.authenticator) {
      options.authenticator = getAuthenticatorFromEnvironment(options.serviceName);
    }
    const service = new DrAutomationServiceV1(options);
    service.configureService(options.serviceName);
    if (options.serviceUrl) {
      service.setServiceUrl(options.serviceUrl);
    }
    return service;
  }

  /**
   * Construct a DrAutomationServiceV1 object.
   *
   * @param {Object} options - Options for the service.
   * @param {string} [options.serviceUrl] - The base URL for the service
   * @param {OutgoingHttpHeaders} [options.headers] - Default headers that shall be included with every request to the service.
   * @param {Authenticator} options.authenticator - The Authenticator object used to authenticate requests to the service
   * @constructor
   * @returns {DrAutomationServiceV1}
   */
  constructor(options: UserOptions) {
    options = options || {};

    super(options);
    if (options.serviceUrl) {
      this.setServiceUrl(options.serviceUrl);
    } else {
      this.setServiceUrl(DrAutomationServiceV1.DEFAULT_SERVICE_URL);
    }
  }

  /*************************
   * drAutomationConfig
   ************************/

  /**
   * Get current API key.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>>}
   */
  public serviceInstanceGetKeyV1(
    params: DrAutomationServiceV1.ServiceInstanceGetKeyV1Params
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceGetKeyV1'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/apikey/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * validate key api.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.apiKey - The API key to validate.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>>}
   */
  public serviceInstanceValidateKey(
    params: DrAutomationServiceV1.ServiceInstanceValidateKeyParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'apiKey'];
    const _validParams = [
      'instanceId',
      'apiKey',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'api_key': _params.apiKey,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceValidateKey'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/apikey/{instance_id}',
        method: 'POST',
        body,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * update api key.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.apiKey -
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>>}
   */
  public serviceInstanceUpdateApiKey(
    params: DrAutomationServiceV1.ServiceInstanceUpdateApiKeyParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidationKeyResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'apiKey'];
    const _validParams = [
      'instanceId',
      'apiKey',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'api_key': _params.apiKey,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceUpdateApiKey'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/apikey/{instance_id}',
        method: 'PUT',
        body,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get GRS location pairs by instance ID.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetGRSLocationPairResponse>>}
   */
  public drGrsLocationPairsDetails(
    params: DrAutomationServiceV1.DrGrsLocationPairsDetailsParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetGRSLocationPairResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'drGrsLocationPairsDetails'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_grs_location_pairs/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get current API key.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetDrLocationsResponse>>}
   */
  public serviceInstanceGetdrlocations(
    params: DrAutomationServiceV1.ServiceInstanceGetdrlocationsParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.GetDrLocationsResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceGetdrlocations'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_locations/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get managed VMs by instance ID.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ManagedVmListResponse>>}
   */
  public drManagedVmsDetails(
    params: DrAutomationServiceV1.DrManagedVmsDetailsParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ManagedVmListResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'drManagedVmsDetails'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_managed_vms/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * DR summary details by instanceID.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrAutomationGetSummaryResponse>>}
   */
  public drSummaryDetails(
    params: DrAutomationServiceV1.DrSummaryDetailsParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DrAutomationGetSummaryResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'drSummaryDetails'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_summary/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Validate  ClusterType API.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.orchestratorClusterType - orchestrator cluster type value.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidateClusterTypeResponse>>}
   */
  public validateClusterType(
    params: DrAutomationServiceV1.ValidateClusterTypeParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidateClusterTypeResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'orchestratorClusterType'];
    const _validParams = [
      'instanceId',
      'orchestratorClusterType',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'orchestrator_cluster_type': _params.orchestratorClusterType,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'validateClusterType'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/validate_cluster_type/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drAutomationIbmCloud
   ************************/

  /**
   * Get MachineTypes by Instance Id.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.primaryWorkspaceName - Primary Workspace Name.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {string} [params.standbyWorkspaceName] - Standby Workspace Name.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.MachineTypesByWorkspace>>}
   */
  public machinetypesDetails(
    params: DrAutomationServiceV1.MachinetypesDetailsParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.MachineTypesByWorkspace>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'primaryWorkspaceName'];
    const _validParams = [
      'instanceId',
      'primaryWorkspaceName',
      'acceptLanguage',
      'ifNoneMatch',
      'standbyWorkspaceName',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'primary_workspace_name': _params.primaryWorkspaceName,
      'standby_workspace_name': _params.standbyWorkspaceName,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'machinetypesDetails'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/machinetypes/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * schematics workspace API.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.SchematicWorkspacesResponse>>}
   */
  public schematicWorkspaceGetoperation(
    params: DrAutomationServiceV1.SchematicWorkspaceGetoperationParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.SchematicWorkspacesResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'schematicWorkspaceGetoperation'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/schematics_workspaces/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Validate powervs workspace API.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.workspaceId - standBy workspaceID value.
   * @param {string} params.crn - crn value.
   * @param {string} params.locationUrl - schematic_workspace_id value.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidateWorkspaceResponse>>}
   */
  public validatePowerVsWorkspace(
    params: DrAutomationServiceV1.ValidatePowerVsWorkspaceParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidateWorkspaceResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'workspaceId', 'crn', 'locationUrl'];
    const _validParams = [
      'instanceId',
      'workspaceId',
      'crn',
      'locationUrl',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'workspace_id': _params.workspaceId,
      'crn': _params.crn,
      'location_url': _params.locationUrl,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'validatePowerVsWorkspace'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/validate_power_vs_workspace/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Validate proxyip.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.proxyip - proxyip value.
   * @param {string} params.vpcLocation - vpc location value.
   * @param {string} params.vpcId - vpc id value.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidateProxyipResponse>>}
   */
  public validateProxyip(
    params: DrAutomationServiceV1.ValidateProxyipParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ValidateProxyipResponse>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'proxyip', 'vpcLocation', 'vpcId'];
    const _validParams = [
      'instanceId',
      'proxyip',
      'vpcLocation',
      'vpcId',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'proxyip': _params.proxyip,
      'vpc_location': _params.vpcLocation,
      'vpc_id': _params.vpcId,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'validateProxyip'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/validate_proxyip/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * workspace API.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.locationId - Location ID value.
   * @param {string} params.vpcId - vpc id value.
   * @param {string} params.tgId - transit gateway id value.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DRData>>}
   */
  public workspaceVpcgetoperation(
    params: DrAutomationServiceV1.WorkspaceVpcgetoperationParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DRData>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'locationId', 'vpcId', 'tgId'];
    const _validParams = [
      'instanceId',
      'locationId',
      'vpcId',
      'tgId',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'location_id': _params.locationId,
      'vpc_id': _params.vpcId,
      'tg_id': _params.tgId,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'workspaceVpcgetoperation'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/workspaces_custom_vpc/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * workspace API.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.schematicId - Schematic ID value.
   * @param {string} params.locationId - Location ID value.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DRData>>}
   */
  public workspaceGetoperation(
    params: DrAutomationServiceV1.WorkspaceGetoperationParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DRData>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'schematicId', 'locationId'];
    const _validParams = [
      'instanceId',
      'schematicId',
      'locationId',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'schematic_id': _params.schematicId,
      'location_id': _params.locationId,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'workspaceGetoperation'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/workspaces_schematic/{instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drAutomationManageDr
   ************************/

  /**
   * DR summary details by instanceID.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>>}
   */
  public serviceInstanceFetchManageDr(
    params: DrAutomationServiceV1.ServiceInstanceFetchManageDrParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceFetchManageDr'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/manage_dr/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * create manageDR a service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} params.standByRedeploy - Flag to indicate if standby should be redeployed (must be "true" or
   * "false").
   * @param {Context} params.context - Contextual information about the DR configuration including workspace details,
   * orchestrator information, and infrastructure specifications.
   * @param {string} params.planId - The identifier of the plan associated with the service instance.
   * @param {string} params.serviceId - The identifier of the service being managed.
   * @param {string} [params.action] - The action to be performed on the service instance.
   * @param {ManageDrParameters} [params.parameters] - Additional service-specific parameters required for DR
   * configuration. These may vary depending on the service being managed.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {boolean} [params.acceptsIncomplete] - A value of true indicates that both the IBM Cloud platform and the
   * requesting client support asynchronous deprovisioning.
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>>}
   */
  public serviceInstanceManageDr(
    params: DrAutomationServiceV1.ServiceInstanceManageDrParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceManageDR>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId', 'standByRedeploy', 'context', 'planId', 'serviceId'];
    const _validParams = [
      'instanceId',
      'standByRedeploy',
      'context',
      'planId',
      'serviceId',
      'action',
      'parameters',
      'acceptLanguage',
      'ifNoneMatch',
      'acceptsIncomplete',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'context': _params.context,
      'plan_id': _params.planId,
      'service_id': _params.serviceId,
      'action': _params.action,
      'parameters': _params.parameters,
    };

    const query = {
      'stand_by_redeploy': _params.standByRedeploy,
      'accepts_incomplete': _params.acceptsIncomplete,
    };

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceManageDr'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/manage_dr/{instance_id}',
        method: 'POST',
        body,
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drAutomationServiceInstance
   ************************/

  /**
   * dr deployment api.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DeploymentStatus>>}
   */
  public serviceInstanceDrdeployment(
    params: DrAutomationServiceV1.ServiceInstanceDrdeploymentParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.DeploymentStatus>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceDrdeployment'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/dr_deployment/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * last operation api.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.instanceId - instance id of instance to provision.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceStatus>>}
   */
  public serviceInstanceLastoperation(
    params: DrAutomationServiceV1.ServiceInstanceLastoperationParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.ServiceInstanceStatus>> {
    const _params = { ...params };
    const _requiredParams = ['instanceId'];
    const _validParams = ['instanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'instance_id': _params.instanceId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceLastoperation'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/last_operation/{instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * drEvents
   ************************/

  /**
   * Get events from this cloud instance since a specific timestamp.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.provisionId - provision id.
   * @param {string} [params.time] - (deprecated - use from_time) A time in either ISO 8601 or unix epoch format.
   * @param {string} [params.fromTime] - A from query time in either ISO 8601 or unix epoch format.
   * @param {string} [params.toTime] - A to query time in either ISO 8601 or unix epoch format.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.Events>>}
   */
  public serviceInstanceEventsGetquery(
    params: DrAutomationServiceV1.ServiceInstanceEventsGetqueryParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.Events>> {
    const _params = { ...params };
    const _requiredParams = ['provisionId'];
    const _validParams = [
      'provisionId',
      'time',
      'fromTime',
      'toTime',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'time': _params.time,
      'from_time': _params.fromTime,
      'to_time': _params.toTime,
    };

    const path = {
      'provision_id': _params.provisionId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceEventsGetquery'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/service_instances/{provision_id}/events',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get a single event.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.provisionId - provision id.
   * @param {string} params.eventId - Event ID.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.Event>>}
   */
  public serviceInstanceEventsGet(
    params: DrAutomationServiceV1.ServiceInstanceEventsGetParams
  ): Promise<DrAutomationServiceV1.Response<DrAutomationServiceV1.Event>> {
    const _params = { ...params };
    const _requiredParams = ['provisionId', 'eventId'];
    const _validParams = [
      'provisionId',
      'eventId',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'provision_id': _params.provisionId,
      'event_id': _params.eventId,
    };

    const sdkHeaders = getSdkHeaders(
      DrAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'serviceInstanceEventsGet'
    );

    const parameters = {
      options: {
        url: '/drautomation/v1/service_instances/{provision_id}/events/{event_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
}

/*************************
 * interfaces
 ************************/

namespace DrAutomationServiceV1 {
  /** An operation response. */
  export interface Response<T = any> {
    result: T;
    status: number;
    statusText: string;
    headers: IncomingHttpHeaders;
  }

  /** The callback for a service request. */
  export type Callback<T> = (error: any, response?: Response<T>) => void;

  /** The body of a service request that returns no response data. */
  export interface EmptyObject {}

  /** A standard JS object, defined to avoid the limitations of `Object` and `object` */
  export interface JsonObject {
    [key: string]: any;
  }

  /*************************
   * request interfaces
   ************************/

  interface DefaultParams {
    headers?: OutgoingHttpHeaders;
    signal?: AbortSignal;
  }

  /** Parameters for the `serviceInstanceGetKeyV1` operation. */
  export interface ServiceInstanceGetKeyV1Params extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `serviceInstanceValidateKey` operation. */
  export interface ServiceInstanceValidateKeyParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The API key to validate. */
    apiKey: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `serviceInstanceUpdateApiKey` operation. */
  export interface ServiceInstanceUpdateApiKeyParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    apiKey: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `drGrsLocationPairsDetails` operation. */
  export interface DrGrsLocationPairsDetailsParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `serviceInstanceGetdrlocations` operation. */
  export interface ServiceInstanceGetdrlocationsParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `drManagedVmsDetails` operation. */
  export interface DrManagedVmsDetailsParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `drSummaryDetails` operation. */
  export interface DrSummaryDetailsParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `validateClusterType` operation. */
  export interface ValidateClusterTypeParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** orchestrator cluster type value. */
    orchestratorClusterType: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `machinetypesDetails` operation. */
  export interface MachinetypesDetailsParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** Primary Workspace Name. */
    primaryWorkspaceName: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
    /** Standby Workspace Name. */
    standbyWorkspaceName?: string;
  }

  /** Parameters for the `schematicWorkspaceGetoperation` operation. */
  export interface SchematicWorkspaceGetoperationParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `validatePowerVsWorkspace` operation. */
  export interface ValidatePowerVsWorkspaceParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** standBy workspaceID value. */
    workspaceId: string;
    /** crn value. */
    crn: string;
    /** schematic_workspace_id value. */
    locationUrl: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `validateProxyip` operation. */
  export interface ValidateProxyipParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** proxyip value. */
    proxyip: string;
    /** vpc location value. */
    vpcLocation: string;
    /** vpc id value. */
    vpcId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `workspaceVpcgetoperation` operation. */
  export interface WorkspaceVpcgetoperationParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** Location ID value. */
    locationId: string;
    /** vpc id value. */
    vpcId: string;
    /** transit gateway id value. */
    tgId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `workspaceGetoperation` operation. */
  export interface WorkspaceGetoperationParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** Schematic ID value. */
    schematicId: string;
    /** Location ID value. */
    locationId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `serviceInstanceFetchManageDr` operation. */
  export interface ServiceInstanceFetchManageDrParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `serviceInstanceManageDr` operation. */
  export interface ServiceInstanceManageDrParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** Flag to indicate if standby should be redeployed (must be "true" or "false"). */
    standByRedeploy: ServiceInstanceManageDrConstants.StandByRedeploy | string;
    /** Contextual information about the DR configuration including workspace details, orchestrator information, and
     *  infrastructure specifications.
     */
    context: Context;
    /** The identifier of the plan associated with the service instance. */
    planId: string;
    /** The identifier of the service being managed. */
    serviceId: string;
    /** The action to be performed on the service instance. */
    action?: string;
    /** Additional service-specific parameters required for DR configuration. These may vary depending on the
     *  service being managed.
     */
    parameters?: ManageDrParameters;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
    /** A value of true indicates that both the IBM Cloud platform and the requesting client support asynchronous
     *  deprovisioning.
     */
    acceptsIncomplete?: boolean;
  }

  /** Constants for the `serviceInstanceManageDr` operation. */
  export namespace ServiceInstanceManageDrConstants {
    /** Flag to indicate if standby should be redeployed (must be "true" or "false"). */
    export enum StandByRedeploy {
      TRUE = 'true',
      FALSE = 'false',
    }
  }

  /** Parameters for the `serviceInstanceDrdeployment` operation. */
  export interface ServiceInstanceDrdeploymentParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `serviceInstanceLastoperation` operation. */
  export interface ServiceInstanceLastoperationParams extends DefaultParams {
    /** instance id of instance to provision. */
    instanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `serviceInstanceEventsGetquery` operation. */
  export interface ServiceInstanceEventsGetqueryParams extends DefaultParams {
    /** provision id. */
    provisionId: string;
    /** (deprecated - use from_time) A time in either ISO 8601 or unix epoch format. */
    time?: string;
    /** A from query time in either ISO 8601 or unix epoch format. */
    fromTime?: string;
    /** A to query time in either ISO 8601 or unix epoch format. */
    toTime?: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `serviceInstanceEventsGet` operation. */
  export interface ServiceInstanceEventsGetParams extends DefaultParams {
    /** provision id. */
    provisionId: string;
    /** Event ID. */
    eventId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /*************************
   * model interfaces
   ************************/

  /**
   * Context.
   *
   * This type supports additional properties of type any.
   */
  export interface Context {
    /**
     * Context accepts additional properties of type any.
     */
    [propName: string]: any;
  }

  /**
   * DRData.
   */
  export interface DRData {
    dr_standby_workspaces: DRStandbyWorkspace[];
    dr_workspaces: DRWorkspace[];
  }

  /**
   * DRStandbyWorkspace.
   */
  export interface DRStandbyWorkspace {
    details?: DetailsDr;
    id?: string;
    location?: LocationDr;
    name?: string;
    status?: string;
  }

  /**
   * DRWorkspace.
   */
  export interface DRWorkspace {
    default?: boolean;
    details?: DetailsDr;
    id?: string;
    location?: LocationDr;
    name?: string;
    status?: string;
  }

  /**
   * DeploymentStatus.
   */
  export interface DeploymentStatus {
    orch_ext_connectivity_status?: string;
    orch_standby_node_addition_status: string;
    orchestrator_cluster_message: string;
    orchestrator_cluster_type: string;
    orchestrator_config_status: string;
    orchestrator_group_leader: string;
    orchestrator_name: string;
    orchestrator_status: string;
    schematic_workspace_name: string;
    schematic_workspace_status: string;
    ssh_key_name: string;
    standby_orchestrator_name: string;
    standby_orchestrator_status: string;
  }

  /**
   * DetailsDr.
   */
  export interface DetailsDr {
    crn?: string;
  }

  /**
   * DrLocation.
   */
  export interface DrLocation {
    id?: string;
    name?: string;
  }

  /**
   * Event.
   */
  export interface Event {
    /** Type of action for this event. */
    action: string;
    /** Source of API when it being executed. */
    api_source?: string;
    /** ID of the Activity. */
    event_id: string;
    /** Level of the event (notice, info, warning, error). */
    level: Event.Constants.Level | string;
    /** The (translated) message of the event. */
    message: string;
    message_data?: JsonObject;
    /** Any metadata associated with the event. */
    metadata?: JsonObject;
    /** Type of resource for this event. */
    resource: string;
    /** Time of activity in ISO 8601 - RFC3339. */
    time: string;
    /** Time of activity in unix epoch. */
    timestamp: string;
    user?: EventUser;
  }
  export namespace Event {
    export namespace Constants {
      /** Level of the event (notice, info, warning, error). */
      export enum Level {
        NOTICE = 'notice',
        INFO = 'info',
        WARNING = 'warning',
        ERROR = 'error',
      }
    }
  }

  /**
   * EventUser.
   */
  export interface EventUser {
    /** Email of the User. */
    email?: string;
    /** Name of the User. */
    name?: string;
    /** ID of user who created/caused the event. */
    user_id: string;
  }

  /**
   * Events.
   */
  export interface Events {
    /** Events. */
    events: Event[];
  }

  /**
   * GetDrLocationsResponse.
   */
  export interface GetDrLocationsResponse {
    dr_locations: DrLocation[];
  }

  /**
   * Response body containing GRS location pairs.
   */
  export interface GetGRSLocationPairResponse {
    /** A map of GRS location pairs where each key is a primary location and the value is its paired location. */
    location_pairs?: JsonObject;
  }

  /**
   * LocationDr.
   */
  export interface LocationDr {
    region?: string;
    type?: string;
    url?: string;
  }

  /**
   * Response body containing machine types grouped by workspace.
   */
  export interface MachineTypesByWorkspace {
    /** Map of workspace IDs to lists of machine types. */
    workspaces?: JsonObject;
  }

  /**
   * Parameters required to manage DR service.
   */
  export interface ManageDrParameters {
    /** The location of the workspace. */
    location?: string;
    /** Parameter required by your service. */
    optional_param?: string;
  }

  /**
   * ManagedVmListResponse.
   */
  export interface ManagedVmListResponse {
    managed_vms: ManagedVmList[];
  }

  /**
   * SchematicWorkspacesResponse.
   */
  export interface SchematicWorkspacesResponse {
    workspaces: DrAutomationSchematicsWorkspace[];
  }

  /**
   * ServiceInstanceManageDR.
   */
  export interface ServiceInstanceManageDR {
    dashboard_url?: string;
    id?: string;
  }

  /**
   * ServiceInstanceStatus.
   */
  export interface ServiceInstanceStatus {
    crn: string;
    deployment_name: string;
    is_ksys_ha: boolean;
    orch_ext_connectivity_status?: string;
    orch_standby_node_addtion_status: string;
    orchestrator_cluster_message: string;
    orchestrator_config_status: string;
    primary_description: string;
    primary_ip_address: string;
    primary_orchestrator_status: string;
    recovery_location: string;
    resource_group: string;
    standby_description: string;
    standby_ip_address: string;
    standby_status: string;
    status: string;
  }

  /**
   * ValidateClusterTypeResponse.
   */
  export interface ValidateClusterTypeResponse {
    description?: string;
    status?: string;
  }

  /**
   * ValidateProxyipResponse.
   */
  export interface ValidateProxyipResponse {
    description?: string;
    status?: string;
    /** Indicates whether the proxy IP is valid but has an advisory (e.g., not in reserved IPs). */
    warning?: boolean;
  }

  /**
   * ValidateWorkspaceResponse.
   */
  export interface ValidateWorkspaceResponse {
    description?: string;
    status?: string;
  }

  /**
   * ValidationKeyResponse.
   */
  export interface ValidationKeyResponse {
    /** Validation result message. */
    description?: string;
    id?: string;
    /** Status of the API key. */
    status?: string;
  }

  /**
   * DrAutomationCatalogRef.
   */
  export interface DrAutomationCatalogRef {
    item_name?: string;
  }

  /**
   * Response object containing all DR automation summary information.
   */
  export interface DrAutomationGetSummaryResponse {
    managed_vm_list: any;
    /** Contains details about the orchestrator configuration. */
    orchestrator_details: OrchestratorDetails;
    /** Contains details about the DR automation service. */
    service_details: ServiceDetails;
  }

  /**
   * DrAutomationSchematicsWorkspace.
   */
  export interface DrAutomationSchematicsWorkspace {
    catalog_ref?: DrAutomationCatalogRef;
    created_at?: string;
    created_by?: string;
    crn?: string;
    description?: string;
    id?: string;
    location?: string;
    name?: string;
    status?: string;
  }

  /**
   * Contains information about a managed VM.
   */
  export interface ManagedVmList {
    /** Unique identifier of the VM. */
    vm_id?: string;
    /** Name of the VM. */
    vm_name?: string;
  }

  /**
   * Contains details about the orchestrator configuration.
   */
  export interface OrchestratorDetails {
    /** Location identifier. */
    location_id: string;
    /** External connectivity status of the orchestrator. */
    orch_ext_connectivity_status: string;
    /** Status of standby node addition. */
    orch_standby_node_addition_status: string;
    /** Message regarding orchestrator cluster status. */
    orchestrator_cluster_message: string;
    /** Type of orchestrator cluster. */
    orchestrator_cluster_type: string;
    /** Configuration status of the orchestrator. */
    orchestrator_config_status: string;
    /** Leader node of the orchestrator group. */
    orchestrator_group_leader: string;
    /** Name of the primary orchestrator. */
    orchestrator_name: string;
    /** Status of the primary orchestrator. */
    orchestrator_status: string;
    /** Name of the orchestrator workspace. */
    orchestrator_workspace_name: string;
    /** IP address of the proxy. */
    proxy_ip: string;
    /** Name of the schematic workspace. */
    schematic_workspace_name: string;
    /** Status of the schematic workspace. */
    schematic_workspace_status: string;
    /** SSH key name used for the orchestrator. */
    ssh_key_name: string;
    /** Name of the standby orchestrator. */
    standby_orchestrator_name: string;
    /** Status of the standby orchestrator. */
    standby_orchestrator_status: string;
    /** Name of the standby orchestrator workspace. */
    standby_orchestrator_workspace_name: string;
    /** Name of the transit gateway. */
    transit_gateway_name: string;
    /** Name of the VPC. */
    vpc_name: string;
  }

  /**
   * Contains details about the DR automation service.
   */
  export interface ServiceDetails {
    /** Cloud Resource Name identifier. */
    crn: string;
    /** Name of the deployment. */
    deployment_name: string;
    /** Description of the primary service. */
    description: string;
    /** Flag indicating if KSYS HA is enabled. */
    is_ksys_ha: boolean;
    /** IP address of the primary service. */
    primary_ip_address: string;
    /** Primary Orchestrator Dashboard URL. */
    primary_orchestrator_dashboard_url: string;
    /** Location for disaster recovery. */
    recovery_location: string;
    /** Resource group name. */
    resource_group: string;
    /** Description of the standby service. */
    standby_description: string;
    /** IP address of the standby service. */
    standby_ip_address: string;
    /** Standby Orchestrator Dashboard URL. */
    standby_orchestrator_dashboard_url: string;
    /** Current status of the standby service. */
    standby_status: string;
    /** Current status of the primary service. */
    status: string;
  }
}

export = DrAutomationServiceV1;
