"use strict";
/**
 * (C) Copyright IBM Corp. 2026.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
/**
 * IBM OpenAPI SDK Code Generator Version: 3.105.0-3c13b041-20250605-193116
 */
var extend = require("extend");
var ibm_cloud_sdk_core_1 = require("ibm-cloud-sdk-core");
var common_1 = require("../lib/common");
/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 1.0.0
 */
var PowerhaAutomationServiceV1 = /** @class */ (function (_super) {
    __extends(PowerhaAutomationServiceV1, _super);
    /**
     * Construct a PowerhaAutomationServiceV1 object.
     *
     * @param {Object} options - Options for the service.
     * @param {string} [options.serviceUrl] - The base URL for the service
     * @param {OutgoingHttpHeaders} [options.headers] - Default headers that shall be included with every request to the service.
     * @param {Authenticator} options.authenticator - The Authenticator object used to authenticate requests to the service
     * @constructor
     * @returns {PowerhaAutomationServiceV1}
     */
    function PowerhaAutomationServiceV1(options) {
        var _this = this;
        options = options || {};
        _this = _super.call(this, options) || this;
        if (options.serviceUrl) {
            _this.setServiceUrl(options.serviceUrl);
        }
        else {
            _this.setServiceUrl(PowerhaAutomationServiceV1.DEFAULT_SERVICE_URL);
        }
        return _this;
    }
    /*************************
     * Factory method
     ************************/
    /**
     * Constructs an instance of PowerhaAutomationServiceV1 with passed in options and external configuration.
     *
     * @param {UserOptions} [options] - The parameters to send to the service.
     * @param {string} [options.serviceName] - The name of the service to configure
     * @param {Authenticator} [options.authenticator] - The Authenticator object used to authenticate requests to the service
     * @param {string} [options.serviceUrl] - The base URL for the service
     * @returns {PowerhaAutomationServiceV1}
     */
    PowerhaAutomationServiceV1.newInstance = function (options) {
        options = options || {};
        if (!options.serviceName) {
            options.serviceName = this.DEFAULT_SERVICE_NAME;
        }
        if (!options.authenticator) {
            options.authenticator = (0, ibm_cloud_sdk_core_1.getAuthenticatorFromEnvironment)(options.serviceName);
        }
        var service = new PowerhaAutomationServiceV1(options);
        service.configureService(options.serviceName);
        if (options.serviceUrl) {
            service.setServiceUrl(options.serviceUrl);
        }
        return service;
    };
    /*************************
     * powerhaAutomationConfig
     ************************/
    /**
     * Update the apikey for the specified PowerHA service instance.
     *
     * Updates a new apikey for the specified PowerHA service instance.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} [params.apiKey] - The API key to be stored or registered.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ApiKeyResponse>>}
     */
    PowerhaAutomationServiceV1.prototype.createApiKey = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId'];
        var _validParams = ['phaInstanceId', 'apiKey', 'acceptLanguage', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var body = {
            'api_key': _params.apiKey,
        };
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'createApiKey');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/api_key/{pha_instance_id}',
                method: 'POST',
                body: body,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Retrieves the cluster node details for the specified PowerHA instance.
     *
     * Retrieves details of all cluster nodes configured for the given PowerHA service instance.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ClusterNodeResponse>>}
     */
    PowerhaAutomationServiceV1.prototype.getClusterNode = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId'];
        var _validParams = ['phaInstanceId', 'ifNoneMatch', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getClusterNode');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/cluster_nodes/{pha_instance_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Add a new cluster node.
     *
     * Adds a new node to the PowerHA cluster for the specified PowerHA service instance.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string[]} params.primaryClusterNodes - List of primary cluster node VM IDs.
     * @param {string[]} [params.secondaryClusterNodes] - List of secondary cluster node VM IDs.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ClusterNodeResponse>>}
     */
    PowerhaAutomationServiceV1.prototype.createClusterNode = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId', 'primaryClusterNodes'];
        var _validParams = [
            'phaInstanceId',
            'primaryClusterNodes',
            'secondaryClusterNodes',
            'acceptLanguage',
            'ifNoneMatch',
            'signal',
            'headers',
        ];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var body = {
            'primary_cluster_nodes': _params.primaryClusterNodes,
            'secondary_cluster_nodes': _params.secondaryClusterNodes,
        };
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'createClusterNode');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/cluster_nodes/{pha_instance_id}',
                method: 'POST',
                body: body,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Delete a cluster node.
     *
     * Removes the specified cluster node from the PowerHA service instance.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} params.vmId - vm ID of workspace.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ClusterNodeResponse>>}
     */
    PowerhaAutomationServiceV1.prototype.deleteClusterNode = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId', 'vmId'];
        var _validParams = ['phaInstanceId', 'vmId', 'ifNoneMatch', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var query = {
            'vm_id': _params.vmId,
        };
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'deleteClusterNode');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/cluster_nodes/{pha_instance_id}',
                method: 'DELETE',
                qs: query,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * List of PowerVS workspaces based on location.
     *
     * Retrieves list of powerVS workspaces related to the PowerHA service instance based on location.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} params.locationId - Location ID value.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaWorkspacesRegionResponse>>}
     */
    PowerhaAutomationServiceV1.prototype.getPowervsWorkspace = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId', 'locationId'];
        var _validParams = [
            'phaInstanceId',
            'locationId',
            'acceptLanguage',
            'ifNoneMatch',
            'signal',
            'headers',
        ];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var query = {
            'location_id': _params.locationId,
        };
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getPowervsWorkspace');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/powervs_workspaces/{pha_instance_id}',
                method: 'GET',
                qs: query,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /*************************
     * powerhaAutomationServiceInstance
     ************************/
    /**
     * View details of the last operation performed on the PowerHA instance.
     *
     * Retrieves the most recent operation performed on the PowerHA service instance.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ServiceInstancePhaStatus>>}
     */
    PowerhaAutomationServiceV1.prototype.getPhaLastOperation = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId'];
        var _validParams = ['phaInstanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getPhaLastOperation');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/last_operation/{pha_instance_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Retrieves deployment details.
     *
     * Retrieves the PowerHA deployment configuration, status, and associated metadata.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaDeploymentResponse>>}
     */
    PowerhaAutomationServiceV1.prototype.getPhaDeployment = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId'];
        var _validParams = ['phaInstanceId', 'ifNoneMatch', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getPhaDeployment');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/pha_deployment/{pha_instance_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Create a new deployment.
     *
     * Create a new PowerHA deployment for a given location and PowerVS workspace. Refer deploying the PowerHA on Powervs
     * https://test.cloud.ibm.com/docs/dr-automation-powervs?topic=dr-automation-powervs-getting-started-with-ha-automation-for-power-virtual-server
     * for more details.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} params.locationId - Identifier for the deployment location.
     * @param {string} params.primaryWorkspace - Primary workspace identifier.
     * @param {string} [params.apiKey] - The API key associated with the request.
     * @param {string} [params.clusterType] - Type of PowerHA cluster being deployed.
     * @param {string} [params.configureType] - Configuration type for the deployment.
     * @param {string[]} [params.primaryClusterNodes] - List of primary cluster node VM IDs.
     * @param {string[]} [params.standbyClusterNodes] - List of standby cluster node VM IDs.
     * @param {string} [params.primaryLocation] - Location identifier for the primary cluster.
     * @param {string} [params.secondaryLocation] - Location identifier for the secondary cluster.
     * @param {string} [params.secondaryWorkspace] - Secondary workspace identifier.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaDeploymentResponse>>}
     */
    PowerhaAutomationServiceV1.prototype.createPhaDeployment = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId', 'locationId', 'primaryWorkspace'];
        var _validParams = [
            'phaInstanceId',
            'locationId',
            'primaryWorkspace',
            'apiKey',
            'clusterType',
            'configureType',
            'primaryClusterNodes',
            'standbyClusterNodes',
            'primaryLocation',
            'secondaryLocation',
            'secondaryWorkspace',
            'acceptLanguage',
            'ifNoneMatch',
            'signal',
            'headers',
        ];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var body = {
            'location_id': _params.locationId,
            'primary_workspace': _params.primaryWorkspace,
            'api_key': _params.apiKey,
            'cluster_type': _params.clusterType,
            'configure_type': _params.configureType,
            'primary_cluster_nodes': _params.primaryClusterNodes,
            'standby_cluster_nodes': _params.standbyClusterNodes,
            'primary_location': _params.primaryLocation,
            'secondary_location': _params.secondaryLocation,
            'secondary_workspace': _params.secondaryWorkspace,
        };
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'createPhaDeployment');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/pha_deployment/{pha_instance_id}',
                method: 'POST',
                body: body,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /*************************
     * powerhaAutomationIbmCloud
     ************************/
    /**
     * Get PowerVS locations.
     *
     * Retrieves the list of PowerVS locations where PowerHA service is supported.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaSupportedLocationsResponse>>}
     */
    PowerhaAutomationServiceV1.prototype.getSupportedLocation = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId'];
        var _validParams = ['phaInstanceId', 'ifNoneMatch', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getSupportedLocation');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/supported_locations/{pha_instance_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /*************************
     * powerhaAutomationEvents
     ************************/
    /**
     * Get PowerHA automation events since a specific timestamp.
     *
     * Get PowerHA automation events since a specific timestamp.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} [params.time] - (deprecated - use from_time) A time in either ISO 8601 or unix epoch format.
     * @param {string} [params.fromTime] - A from query time in either ISO 8601 or unix epoch format.
     * @param {string} [params.toTime] - A to query time in either ISO 8601 or unix epoch format.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaEventCollection>>}
     */
    PowerhaAutomationServiceV1.prototype.listServiceInstanceEvents = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId'];
        var _validParams = [
            'phaInstanceId',
            'time',
            'fromTime',
            'toTime',
            'acceptLanguage',
            'ifNoneMatch',
            'signal',
            'headers',
        ];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var query = {
            'time': _params.time,
            'from_time': _params.fromTime,
            'to_time': _params.toTime,
        };
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'listServiceInstanceEvents');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/service_instances/{pha_instance_id}/events',
                method: 'GET',
                qs: query,
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Get a single PowerHA automation event.
     *
     * Get a single PowerHA automation event.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} params.eventId - Event ID.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaEvent>>}
     */
    PowerhaAutomationServiceV1.prototype.getServiceInstanceEvent = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId', 'eventId'];
        var _validParams = [
            'phaInstanceId',
            'eventId',
            'acceptLanguage',
            'ifNoneMatch',
            'signal',
            'headers',
        ];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'pha_instance_id': _params.phaInstanceId,
            'event_id': _params.eventId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getServiceInstanceEvent');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/service_instances/{pha_instance_id}/events/{event_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /*************************
     * powerhaAutomationAgent
     ************************/
    /**
     * Get the Job status of the downloaded powerHA agent file.
     *
     * Returns the current status of the job associated with a PowerHA agent file download. It indicates whether the
     * download job is in running, completed, or failed, along with relevant metadata such as job ID, Job creation time
     * and last updated time.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} params.phaJobId - Unique ID to track the pha agent file download.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaAgentJobStatusResponse>>}
     */
    PowerhaAutomationServiceV1.prototype.getPhaAgentFileDownloadJobStatus = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId', 'phaJobId'];
        var _validParams = [
            'phaInstanceId',
            'phaJobId',
            'acceptLanguage',
            'ifNoneMatch',
            'signal',
            'headers',
        ];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'pha_instance_id': _params.phaInstanceId,
            'pha_job_id': _params.phaJobId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'getPhaAgentFileDownloadJobStatus');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/pha_agent/download/{pha_instance_id}/jobs/{pha_job_id}',
                method: 'GET',
                path: path,
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/json',
                    'Accept-Language': _params.acceptLanguage,
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    /**
     * Downloads PowerHA Agent file.
     *
     * Validates the pvm instance and then creates a job for the download process, downloads the PowerHA agent file from
     * the Cloud Object Storage (COS) location, and updates the job progress in real time. Users can use the job ID to
     * query the download status, including whether the job is running, completed, or failed.
     *
     * @param {Object} params - The parameters to send to the service.
     * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
     * @param {string} [params.acceptLanguage] - The language requested for the return document.
     * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
     * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
     * @returns {Promise<PowerhaAutomationServiceV1.Response<NodeJS.ReadableStream>>}
     */
    PowerhaAutomationServiceV1.prototype.downloadPhaAgentFile = function (params) {
        var _params = __assign({}, params);
        var _requiredParams = ['phaInstanceId'];
        var _validParams = ['phaInstanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
        var _validationErrors = (0, ibm_cloud_sdk_core_1.validateParams)(_params, _requiredParams, _validParams);
        if (_validationErrors) {
            return Promise.reject(_validationErrors);
        }
        var path = {
            'pha_instance_id': _params.phaInstanceId,
        };
        var sdkHeaders = (0, common_1.getSdkHeaders)(PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME, 'v1', 'downloadPhaAgentFile');
        var parameters = {
            options: {
                url: '/powerha_automation/v1/pha_agent/download/{pha_instance_id}',
                method: 'GET',
                path: path,
                responseType: 'stream',
            },
            defaultOptions: extend(true, {}, this.baseOptions, {
                headers: extend(true, sdkHeaders, this.baseOptions.headers, {
                    'Accept': 'application/octet-stream',
                    'Accept-Language': _params.acceptLanguage,
                    'If-None-Match': _params.ifNoneMatch,
                }, _params.headers),
                axiosOptions: {
                    signal: _params.signal,
                },
            }),
        };
        return this.createRequest(parameters);
    };
    PowerhaAutomationServiceV1.DEFAULT_SERVICE_URL = 'https://power-dra.cloud.ibm.com';
    PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME = 'powerha_automation_service';
    return PowerhaAutomationServiceV1;
}(ibm_cloud_sdk_core_1.BaseService));
/*************************
 * interfaces
 ************************/
(function (PowerhaAutomationServiceV1) {
    var PhaEvent;
    (function (PhaEvent) {
        var Constants;
        (function (Constants) {
            /** Level of the event (notice, info, warning, error). */
            var Level;
            (function (Level) {
                Level["NOTICE"] = "notice";
                Level["INFO"] = "info";
                Level["WARNING"] = "warning";
                Level["ERROR"] = "error";
            })(Level = Constants.Level || (Constants.Level = {}));
        })(Constants = PhaEvent.Constants || (PhaEvent.Constants = {}));
    })(PhaEvent = PowerhaAutomationServiceV1.PhaEvent || (PowerhaAutomationServiceV1.PhaEvent = {}));
})(PowerhaAutomationServiceV1 || (PowerhaAutomationServiceV1 = {}));
module.exports = PowerhaAutomationServiceV1;
//# sourceMappingURL=v1.js.map