/**
 * (C) Copyright IBM Corp. 2026.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * IBM OpenAPI SDK Code Generator Version: 3.113.0-3f9df07a-20260317-160650
 */

import * as extend from 'extend';
import { IncomingHttpHeaders, OutgoingHttpHeaders } from 'http';
import {
  AbortSignal,
  Authenticator,
  BaseService,
  UserOptions,
  getAuthenticatorFromEnvironment,
  validateParams,
} from 'ibm-cloud-sdk-core';
import { getSdkHeaders } from '../lib/common';

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API Version: 1.0.0
 */

class PowerhaAutomationServiceV1 extends BaseService {
  static DEFAULT_SERVICE_URL: string = 'https://power-dra.test.cloud.ibm.com';

  static DEFAULT_SERVICE_NAME: string = 'powerha_automation_service';

  /*************************
   * Factory method
   ************************/

  /**
   * Constructs an instance of PowerhaAutomationServiceV1 with passed in options and external configuration.
   *
   * @param {UserOptions} [options] - The parameters to send to the service.
   * @param {string} [options.serviceName] - The name of the service to configure
   * @param {Authenticator} [options.authenticator] - The Authenticator object used to authenticate requests to the service
   * @param {string} [options.serviceUrl] - The base URL for the service
   * @returns {PowerhaAutomationServiceV1}
   */

  public static newInstance(options: UserOptions): PowerhaAutomationServiceV1 {
    options = options || {};

    if (!options.serviceName) {
      options.serviceName = this.DEFAULT_SERVICE_NAME;
    }
    if (!options.authenticator) {
      options.authenticator = getAuthenticatorFromEnvironment(options.serviceName);
    }
    const service = new PowerhaAutomationServiceV1(options);
    service.configureService(options.serviceName);
    if (options.serviceUrl) {
      service.setServiceUrl(options.serviceUrl);
    }
    return service;
  }

  /**
   * Construct a PowerhaAutomationServiceV1 object.
   *
   * @param {Object} options - Options for the service.
   * @param {string} [options.serviceUrl] - The base URL for the service
   * @param {OutgoingHttpHeaders} [options.headers] - Default headers that shall be included with every request to the service.
   * @param {Authenticator} options.authenticator - The Authenticator object used to authenticate requests to the service
   * @constructor
   * @returns {PowerhaAutomationServiceV1}
   */
  constructor(options: UserOptions) {
    options = options || {};

    super(options);
    if (options.serviceUrl) {
      this.setServiceUrl(options.serviceUrl);
    } else {
      this.setServiceUrl(PowerhaAutomationServiceV1.DEFAULT_SERVICE_URL);
    }
  }

  /*************************
   * powerhaAutomationConfig
   ************************/

  /**
   * Get the apikey for the specified PowerHA service instance.
   *
   * Retrieves existing apikey for the specified PowerHA service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ApiKeyResponse>>}
   */
  public getApiKey(
    params: PowerhaAutomationServiceV1.GetApiKeyParams
  ): Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ApiKeyResponse>> {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId'];
    const _validParams = ['phaInstanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getApiKey'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/api_key/{pha_instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Update the apikey for the specified PowerHA service instance.
   *
   * Updates a new apikey for the specified PowerHA service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} [params.apiKey] - The API key to be stored or registered.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ApiKeyResponse>>}
   */
  public createApiKey(
    params: PowerhaAutomationServiceV1.CreateApiKeyParams
  ): Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ApiKeyResponse>> {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId'];
    const _validParams = [
      'phaInstanceId',
      'apiKey',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'api_key': _params.apiKey,
    };

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'createApiKey'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/api_key/{pha_instance_id}',
        method: 'POST',
        body,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Retrieves the cluster node details for the specified PowerHA instance.
   *
   * Retrieves details of all cluster nodes configured for the given PowerHA service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ClusterNodeResponse>>}
   */
  public getClusterNode(
    params: PowerhaAutomationServiceV1.GetClusterNodeParams
  ): Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ClusterNodeResponse>> {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId'];
    const _validParams = ['phaInstanceId', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getClusterNode'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/cluster_nodes/{pha_instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Add a new cluster node.
   *
   * Adds a new node to the PowerHA cluster for the specified PowerHA service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string[]} params.primaryClusterNodes - List of primary cluster node VM IDs.
   * @param {string[]} [params.secondaryClusterNodes] - List of secondary cluster node VM IDs.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ClusterNodeResponse>>}
   */
  public createClusterNode(
    params: PowerhaAutomationServiceV1.CreateClusterNodeParams
  ): Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ClusterNodeResponse>> {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId', 'primaryClusterNodes'];
    const _validParams = [
      'phaInstanceId',
      'primaryClusterNodes',
      'secondaryClusterNodes',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'primary_cluster_nodes': _params.primaryClusterNodes,
      'secondary_cluster_nodes': _params.secondaryClusterNodes,
    };

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'createClusterNode'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/cluster_nodes/{pha_instance_id}',
        method: 'POST',
        body,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Delete a cluster node.
   *
   * Removes the specified cluster node from the PowerHA service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} params.vmId - vm ID of workspace.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ClusterNodeResponse>>}
   */
  public deleteClusterNode(
    params: PowerhaAutomationServiceV1.DeleteClusterNodeParams
  ): Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ClusterNodeResponse>> {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId', 'vmId'];
    const _validParams = ['phaInstanceId', 'vmId', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'vm_id': _params.vmId,
    };

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'deleteClusterNode'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/cluster_nodes/{pha_instance_id}',
        method: 'DELETE',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * List of PowerVS workspaces based on location.
   *
   * Retrieves list of powerVS workspaces related to the PowerHA service instance based on location.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} params.locationId - Location ID value.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaWorkspacesRegionResponse>>}
   */
  public getPowervsWorkspace(
    params: PowerhaAutomationServiceV1.GetPowervsWorkspaceParams
  ): Promise<
    PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaWorkspacesRegionResponse>
  > {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId', 'locationId'];
    const _validParams = [
      'phaInstanceId',
      'locationId',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'location_id': _params.locationId,
    };

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getPowervsWorkspace'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/powervs_workspaces/{pha_instance_id}',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * powerhaAutomationServiceInstance
   ************************/

  /**
   * View details of the last operation performed on the PowerHA instance.
   *
   * Retrieves the most recent operation performed on the PowerHA service instance.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ServiceInstancePhaStatus>>}
   */
  public getPhaLastOperation(
    params: PowerhaAutomationServiceV1.GetPhaLastOperationParams
  ): Promise<
    PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.ServiceInstancePhaStatus>
  > {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId'];
    const _validParams = ['phaInstanceId', 'acceptLanguage', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getPhaLastOperation'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/last_operation/{pha_instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Retrieves deployment details.
   *
   * Retrieves the PowerHA deployment configuration, status, and associated metadata.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaDeploymentResponse>>}
   */
  public getPhaDeployment(
    params: PowerhaAutomationServiceV1.GetPhaDeploymentParams
  ): Promise<
    PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaDeploymentResponse>
  > {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId'];
    const _validParams = ['phaInstanceId', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getPhaDeployment'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/pha_deployment/{pha_instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Create a new deployment.
   *
   * Create a new PowerHA deployment for a given location and PowerVS workspace. Refer deploying the PowerHA on Powervs
   * https://test.cloud.ibm.com/docs/dr-automation-powervs?topic=dr-automation-powervs-getting-started-with-ha-automation-for-power-virtual-server
   * for more details.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} params.locationId - Identifier for the deployment location.
   * @param {string} params.primaryWorkspace - Primary workspace identifier.
   * @param {string} [params.apiKey] - The API key associated with the request.
   * @param {string} [params.clusterType] - Type of PowerHA cluster being deployed.
   * @param {string} [params.configureType] - Configuration type for the deployment.
   * @param {string[]} [params.primaryClusterNodes] - List of primary cluster node VM IDs.
   * @param {string[]} [params.standbyClusterNodes] - List of standby cluster node VM IDs.
   * @param {string} [params.primaryLocation] - Location identifier for the primary cluster.
   * @param {string} [params.secondaryLocation] - Location identifier for the secondary cluster.
   * @param {string} [params.secondaryWorkspace] - Secondary workspace identifier.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaDeploymentResponse>>}
   */
  public createPhaDeployment(
    params: PowerhaAutomationServiceV1.CreatePhaDeploymentParams
  ): Promise<
    PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaDeploymentResponse>
  > {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId', 'locationId', 'primaryWorkspace'];
    const _validParams = [
      'phaInstanceId',
      'locationId',
      'primaryWorkspace',
      'apiKey',
      'clusterType',
      'configureType',
      'primaryClusterNodes',
      'standbyClusterNodes',
      'primaryLocation',
      'secondaryLocation',
      'secondaryWorkspace',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const body = {
      'location_id': _params.locationId,
      'primary_workspace': _params.primaryWorkspace,
      'api_key': _params.apiKey,
      'cluster_type': _params.clusterType,
      'configure_type': _params.configureType,
      'primary_cluster_nodes': _params.primaryClusterNodes,
      'standby_cluster_nodes': _params.standbyClusterNodes,
      'primary_location': _params.primaryLocation,
      'secondary_location': _params.secondaryLocation,
      'secondary_workspace': _params.secondaryWorkspace,
    };

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'createPhaDeployment'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/pha_deployment/{pha_instance_id}',
        method: 'POST',
        body,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * powerhaAutomationIbmCloud
   ************************/

  /**
   * Get PowerVS locations.
   *
   * Retrieves the list of PowerVS locations where PowerHA service is supported.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaSupportedLocationsResponse>>}
   */
  public getSupportedLocation(
    params: PowerhaAutomationServiceV1.GetSupportedLocationParams
  ): Promise<
    PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaSupportedLocationsResponse>
  > {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId'];
    const _validParams = ['phaInstanceId', 'ifNoneMatch', 'signal', 'headers'];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getSupportedLocation'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/supported_locations/{pha_instance_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * powerhaAutomationEvents
   ************************/

  /**
   * Get PowerHA automation events from this cloud instance since a specific timestamp.
   *
   * Get PowerHA automation events from this cloud instance since a specific timestamp.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} [params.time] - (deprecated - use from_time) A time in either ISO 8601 or unix epoch format.
   * @param {string} [params.fromTime] - A from query time in either ISO 8601 or unix epoch format.
   * @param {string} [params.toTime] - A to query time in either ISO 8601 or unix epoch format.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaEventCollection>>}
   */
  public listServiceInstanceEvents(
    params: PowerhaAutomationServiceV1.ListServiceInstanceEventsParams
  ): Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaEventCollection>> {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId'];
    const _validParams = [
      'phaInstanceId',
      'time',
      'fromTime',
      'toTime',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const query = {
      'time': _params.time,
      'from_time': _params.fromTime,
      'to_time': _params.toTime,
    };

    const path = {
      'pha_instance_id': _params.phaInstanceId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'listServiceInstanceEvents'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/service_instances/{pha_instance_id}/events',
        method: 'GET',
        qs: query,
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Get a single PowerHA automation event.
   *
   * Get a single PowerHA automation event.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} params.eventId - Event ID.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaEvent>>}
   */
  public getServiceInstanceEvent(
    params: PowerhaAutomationServiceV1.GetServiceInstanceEventParams
  ): Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaEvent>> {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId', 'eventId'];
    const _validParams = [
      'phaInstanceId',
      'eventId',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'pha_instance_id': _params.phaInstanceId,
      'event_id': _params.eventId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getServiceInstanceEvent'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/service_instances/{pha_instance_id}/events/{event_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
  /*************************
   * powerhaAutomationAgent
   ************************/

  /**
   * Get the Job status of the downloaded powerHA agent file.
   *
   * Returns the current status of the job associated with a PowerHA agent file download. It indicates whether the
   * download job is in running, completed, or failed, along with relevant metadata such as job ID, Job creation time
   * and last updated time.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} params.phaJobId - Unique ID to track the pha agent file download.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaAgentJobStatusResponse>>}
   */
  public getPhaAgentFileDownloadJobStatus(
    params: PowerhaAutomationServiceV1.GetPhaAgentFileDownloadJobStatusParams
  ): Promise<
    PowerhaAutomationServiceV1.Response<PowerhaAutomationServiceV1.PhaAgentJobStatusResponse>
  > {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId', 'phaJobId'];
    const _validParams = [
      'phaInstanceId',
      'phaJobId',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'pha_instance_id': _params.phaInstanceId,
      'pha_job_id': _params.phaJobId,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'getPhaAgentFileDownloadJobStatus'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/pha_agent/download/{pha_instance_id}/jobs/{pha_job_id}',
        method: 'GET',
        path,
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/json',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }

  /**
   * Downloads PowerHA Agent file.
   *
   * Validates the pvm instance and then creates a job for the download process, downloads the PowerHA agent file from
   * the Cloud Object Storage (COS) location, and updates the job progress in real time. Users can use the job ID to
   * query the download status, including whether the job is running, completed, or failed.
   *
   * @param {Object} params - The parameters to send to the service.
   * @param {string} params.phaInstanceId - Unique identifier of the provisioned instance.
   * @param {string} params.phaPvmInstanceName - Power Virtual Machine Instance Name.
   * @param {string} [params.acceptLanguage] - The language requested for the return document.
   * @param {string} [params.ifNoneMatch] - ETag for conditional requests (optional).
   * @param {OutgoingHttpHeaders} [params.headers] - Custom request headers
   * @returns {Promise<PowerhaAutomationServiceV1.Response<NodeJS.ReadableStream>>}
   */
  public downloadPhaAgentFile(
    params: PowerhaAutomationServiceV1.DownloadPhaAgentFileParams
  ): Promise<PowerhaAutomationServiceV1.Response<NodeJS.ReadableStream>> {
    const _params = { ...params };
    const _requiredParams = ['phaInstanceId', 'phaPvmInstanceName'];
    const _validParams = [
      'phaInstanceId',
      'phaPvmInstanceName',
      'acceptLanguage',
      'ifNoneMatch',
      'signal',
      'headers',
    ];
    const _validationErrors = validateParams(_params, _requiredParams, _validParams);
    if (_validationErrors) {
      return Promise.reject(_validationErrors);
    }

    const path = {
      'pha_instance_id': _params.phaInstanceId,
      'pha_pvm_instance_name': _params.phaPvmInstanceName,
    };

    const sdkHeaders = getSdkHeaders(
      PowerhaAutomationServiceV1.DEFAULT_SERVICE_NAME,
      'v1',
      'downloadPhaAgentFile'
    );

    const parameters = {
      options: {
        url: '/powerha_automation/v1/pha_agent/download/{pha_instance_id}/vm_instance/{pha_pvm_instance_name}',
        method: 'GET',
        path,
        responseType: 'stream',
      },
      defaultOptions: extend(true, {}, this.baseOptions, {
        headers: extend(
          true,
          sdkHeaders,
          this.baseOptions.headers,
          {
            'Accept': 'application/octet-stream',
            'Accept-Language': _params.acceptLanguage,
            'If-None-Match': _params.ifNoneMatch,
          },
          _params.headers
        ),
        axiosOptions: {
          signal: _params.signal,
        },
      }),
    };

    return this.createRequest(parameters);
  }
}

/*************************
 * interfaces
 ************************/

namespace PowerhaAutomationServiceV1 {
  /** An operation response. */
  export interface Response<T = any> {
    result: T;
    status: number;
    statusText: string;
    headers: IncomingHttpHeaders;
  }

  /** The callback for a service request. */
  export type Callback<T> = (error: any, response?: Response<T>) => void;

  /** The body of a service request that returns no response data. */
  export interface EmptyObject {}

  /** A standard JS object, defined to avoid the limitations of `Object` and `object` */
  export interface JsonObject {
    [key: string]: any;
  }

  /*************************
   * request interfaces
   ************************/

  interface DefaultParams {
    headers?: OutgoingHttpHeaders;
    signal?: AbortSignal;
  }

  /** Parameters for the `getApiKey` operation. */
  export interface GetApiKeyParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `createApiKey` operation. */
  export interface CreateApiKeyParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** The API key to be stored or registered. */
    apiKey?: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getClusterNode` operation. */
  export interface GetClusterNodeParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `createClusterNode` operation. */
  export interface CreateClusterNodeParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** List of primary cluster node VM IDs. */
    primaryClusterNodes: string[];
    /** List of secondary cluster node VM IDs. */
    secondaryClusterNodes?: string[];
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `deleteClusterNode` operation. */
  export interface DeleteClusterNodeParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** vm ID of workspace. */
    vmId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getPowervsWorkspace` operation. */
  export interface GetPowervsWorkspaceParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** Location ID value. */
    locationId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getPhaLastOperation` operation. */
  export interface GetPhaLastOperationParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getPhaDeployment` operation. */
  export interface GetPhaDeploymentParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `createPhaDeployment` operation. */
  export interface CreatePhaDeploymentParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** Identifier for the deployment location. */
    locationId: string;
    /** Primary workspace identifier. */
    primaryWorkspace: string;
    /** The API key associated with the request. */
    apiKey?: string;
    /** Type of PowerHA cluster being deployed. */
    clusterType?: string;
    /** Configuration type for the deployment. */
    configureType?: string;
    /** List of primary cluster node VM IDs. */
    primaryClusterNodes?: string[];
    /** List of standby cluster node VM IDs. */
    standbyClusterNodes?: string[];
    /** Location identifier for the primary cluster. */
    primaryLocation?: string;
    /** Location identifier for the secondary cluster. */
    secondaryLocation?: string;
    /** Secondary workspace identifier. */
    secondaryWorkspace?: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getSupportedLocation` operation. */
  export interface GetSupportedLocationParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `listServiceInstanceEvents` operation. */
  export interface ListServiceInstanceEventsParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** (deprecated - use from_time) A time in either ISO 8601 or unix epoch format. */
    time?: string;
    /** A from query time in either ISO 8601 or unix epoch format. */
    fromTime?: string;
    /** A to query time in either ISO 8601 or unix epoch format. */
    toTime?: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getServiceInstanceEvent` operation. */
  export interface GetServiceInstanceEventParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** Event ID. */
    eventId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `getPhaAgentFileDownloadJobStatus` operation. */
  export interface GetPhaAgentFileDownloadJobStatusParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** Unique ID to track the pha agent file download. */
    phaJobId: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /** Parameters for the `downloadPhaAgentFile` operation. */
  export interface DownloadPhaAgentFileParams extends DefaultParams {
    /** Unique identifier of the provisioned instance. */
    phaInstanceId: string;
    /** Power Virtual Machine Instance Name. */
    phaPvmInstanceName: string;
    /** The language requested for the return document. */
    acceptLanguage?: string;
    /** ETag for conditional requests (optional). */
    ifNoneMatch?: string;
  }

  /*************************
   * model interfaces
   ************************/

  /**
   * Response containing details of a stored API key.
   */
  export interface ApiKeyResponse {
    /** The API key associated with the request. */
    api_key: string;
    /** Unique identifier for the API key record. */
    id: string;
  }

  /**
   * Information about a cluster node participating in the PHA environment.
   */
  export interface ClusterNodeInfo {
    /** Status of the PHA agent running on the node. */
    agent_status?: string;
    /** Number of CPU cores allocated to the node. */
    cores?: number;
    /** IP address assigned to the virtual machine. */
    ip_address?: string;
    /** Memory allocated to the virtual machine in MB or GB. */
    memory?: number;
    /** PowerHA version level installed on the node. */
    pha_level?: string;
    /** Region where the virtual machine is deployed. */
    region?: string;
    /** Unique identifier of the virtual machine. */
    vm_id?: string;
    /** Name of the virtual machine. */
    vm_name?: string;
    /** Current operational status of the virtual machine. */
    vm_status?: string;
    /** Workspace identifier associated with the node. */
    workspace_id?: string;
  }

  /**
   * Response schema for retrieving cluster node information.
   */
  export interface ClusterNodeResponse {
    /** Identifier for this cluster node response. */
    id?: string;
    /** Details of the primary cluster nodes. */
    primary_node_details: NodeDetail[];
    /** Details of the secondary cluster nodes. */
    secondary_node_details: NodeDetail[];
  }

  /**
   * Details of a virtual machine (VM) participating in the cluster.
   */
  export interface NodeDetail {
    /** Status of the PHA agent running on the node. */
    agent_status?: string;
    /** Number of CPU cores allocated to the VM. */
    cores?: number;
    /** List of IP addresses assigned to the VM. */
    ip_addresses: string[];
    /** Amount of memory allocated to the VM (in GB). */
    memory?: number;
    /** PowerHA version level installed on the node. */
    pha_level?: string;
    /** Region where the VM is deployed. */
    region?: string;
    /** Unique identifier of the VM. */
    vm_id?: string;
    /** Name of the VM. */
    vm_name?: string;
    /** Current status of the VM. */
    vm_status?: string;
    /** ID of the workspace associated with the VM. */
    workspace_id?: string;
  }

  /**
   * Status information of a PowerHA agent job.
   */
  export interface PhaAgentJobStatusResponse {
    /** Number of bytes downloaded so far. */
    bytes_downloaded?: number;
    /** Timestamp when the job was created. */
    creation_at?: string;
    /** Name of the file that has been downloaded. */
    file_name?: string;
    /** Unique identifier of the job. */
    job_id?: string;
    /** Timestamp of the last update for this status. */
    last_updated_at?: string;
    /** Identifier of the service instance associated with the deployment. */
    service_instance_id?: string;
    /** Current status of the deployment (e.g., running, completed, failed). */
    status?: string;
    /** Total size in bytes of the file that has to be downloaded. */
    total_bytes?: number;
    /** Identifier of the virtual machine involved in the deployment. */
    vm_id?: string;
  }

  /**
   * Details of a PowerHA deployment including cluster information, provisioning status, network configuration, and
   * associated resources.
   */
  export interface PhaDeploymentResponse {
    /** API key used for authentication to the deployment service. */
    api_key?: string;
    /** Cloud account identifier. */
    cloud_account_id?: string;
    /** Type of network connectivity. */
    connectivity_type?: string;
    /** Timestamp expressing creation time. */
    creation_time?: string;
    /** List of custom network CIDRs. */
    custom_network: string[];
    /** Timestamp expressing deprovision time. */
    deprovision_time?: string;
    /** Global unique identifier. */
    guid?: string;
    /** Indicates whether deployment is duplicate. */
    is_duplicate?: boolean;
    /** Identifier for the service plan. */
    plan_id?: string;
    /** Name of service plan. */
    plan_name?: string;
    /** Name of the PowerHA cluster. */
    powerha_cluster_name?: string;
    /** Type of PowerHA cluster. */
    powerha_cluster_type?: string;
    /** PowerHA version level. */
    powerha_level?: string;
    /** List of primary cluster nodes. */
    primary_cluster_nodes: ClusterNodeInfo[];
    /** Primary cluster location. */
    primary_location?: string;
    /** name of the primary workspace region. */
    primary_region_name?: string;
    /** Primary workspace identifier. */
    primary_workspace?: string;
    /** name of the primary workspace. */
    primary_workspace_name?: string;
    /** Time stamp provisioning completed. */
    provision_end_time?: string;
    /** Provision request identifier. */
    id?: string;
    /** Time stamp provisioning started. */
    provision_start_time?: string;
    /** Current provision status. */
    provision_status?: string;
    /** Deployment region identifier. */
    region_id?: string;
    /** Name of the resource group. */
    resource_group?: string;
    /** CRN of associated resource group. */
    resource_group_crn?: string;
    /** Resource instance identifier. */
    resource_instance?: string;
    /** List of secondary cluster nodes. */
    secondary_cluster_nodes: ClusterNodeInfo[];
    /** Secondary cluster location. */
    secondary_location?: string;
    /** Secondary workspace identifier. */
    secondary_workspace?: string;
    /** Description of provisioned service. */
    service_description?: string;
    /** Identifier for the service. */
    service_id?: string;
    /** Name of service. */
    service_name?: string;
    /** name of the standby workspace region. */
    standby_region_name?: string;
    /** name of the standby workspace. */
    standby_workspace_name?: string;
    /** User defined tags. */
    user_tags?: string;
  }

  /**
   * pha events.
   */
  export interface PhaEvent {
    /** Type of action for this event. */
    action: string;
    /** Source of API when it being executed. */
    api_source?: string;
    /** ID of the Activity. */
    event_id: string;
    /** Level of the event (notice, info, warning, error). */
    level: PhaEvent.Constants.Level | string;
    /** The (translated) message of the event. */
    message: string;
    /** Dynamic key-value data related to the event message. */
    message_data?: JsonObject;
    /** Metadata providing additional context for the event. */
    meta_data?: JsonObject;
    /** Type of resource for this event. */
    resource: string;
    /** Time of activity in ISO 8601 - RFC3339. */
    time: string;
    /** Timestamp indicating when the event occurred. */
    time_stamp: string;
    /** events for pha user. */
    user?: PhaEventUser;
  }
  export namespace PhaEvent {
    export namespace Constants {
      /** Level of the event (notice, info, warning, error). */
      export enum Level {
        NOTICE = 'notice',
        INFO = 'info',
        WARNING = 'warning',
        ERROR = 'error',
      }
    }
  }

  /**
   * event collection for pha.
   */
  export interface PhaEventCollection {
    /** Pha automation Events. */
    events: PhaEvent[];
  }

  /**
   * events for pha user.
   */
  export interface PhaEventUser {
    /** Email of the User. */
    email?: string;
    /** Name of the User. */
    name?: string;
    /** ID of user who created/caused the event. */
    user_id: string;
  }

  /**
   * Details of a PowerHA supported location.
   */
  export interface PhaLocation {
    /** Unique identifier for the location. */
    id?: string;
    /** Human-readable name of the location. */
    name?: string;
  }

  /**
   * List of PowerVS locations where PowerHA service is supported.
   */
  export interface PhaSupportedLocationsResponse {
    /** Array of PowerVS locations where PowerHA service is supported. */
    locations: PhaLocation[];
  }

  /**
   * Summary information for a PowerHA workspace.
   */
  export interface PhaWorkspaceSummary {
    /** Unique identifier of the workspace. */
    id?: string;
    /** Name of the workspace. */
    name?: string;
  }

  /**
   * Response containing the list of workspaces for a specific region.
   */
  export interface PhaWorkspacesRegionResponse {
    /** Array of workspace summaries within the region. */
    workspaces: PhaWorkspaceSummary[];
  }

  /**
   * Current status information for a PHA service instance.
   */
  export interface ServiceInstancePhaStatus {
    /** Name of the deployment associated with the service instance. */
    deployment_name: string;
    /** Unique identifier for the provisioning operation. */
    provision_id: string;
    /** Resource Group. */
    resource_group: string;
    /** Current operational status of the service instance. */
    status: string;
  }
}

export = PowerhaAutomationServiceV1;
